### ISSUE TITLE
Flapping test t/spec/MISC/bug-coverage-stress-6.d.t

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#1029]
Noticed this the other day on my RPi 2. Today I found a way to repro it on my Linux system as well. I had to load the system down a tad, e.g. by starting a spectest in another terminal window which uses up all available cores.

Here's what it looks like:

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6-gdb-m  t/spec/MISC/bug-coverage-stress-6.d.t
    ================================================================================================
    This is Rakudo Perl 6 running in the GNU debugger, which often allows the user to generate useful back-
    traces to debug or report issues in Rakudo, the MoarVM backend or the currently running code.
    
    This Rakudo version is 2018.12.116.gd.836.ca.4 built on MoarVM version 2018.12.13.g.473324.e,
    running on linuxmint (18.3.Sylvia) / linux (4.10.0.38.generic)
    
    Type `bt full` to generate a backtrace if applicable, type `q` to quit or `help` for help.
    ------------------------------------------------------------------------------------------------
    Reading symbols from /home/dogbert/repos/rakudo/nqp/MoarVM/../../install/bin/moar...done.
    Starting program: /home/dogbert/repos/rakudo/install/bin/moar --execname=./perl6-gdb-m --libpath=. --libpath=blib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib /home/dogbert/repos/rakudo/perl6.moarvm --nqp-lib=blib t/spec/MISC/bug-coverage-stress-6.d.t
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    ...
    (gdb) b continuation.c:151
    Breakpoint 1 at 0x7ffff5c761d7: file src/core/continuation.c, line 151.
    (gdb) r
    Starting program: /home/dogbert/repos/rakudo/install/bin/moar --execname=./perl6-gdb-m --libpath=. --libpath=blib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib /home/dogbert/repos/rakudo/perl6.moarvm --nqp-lib=blib t/spec/MISC/bug-coverage-stress-6.d.t
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7ffff209a700 (LWP 27933)]
    1..1
    [New Thread 0x7fffec224700 (LWP 28011)]
    [New Thread 0x7fffeba23700 (LWP 28012)]
    [New Thread 0x7fffeb181700 (LWP 28015)]
    [New Thread 0x7fffea91f700 (LWP 28016)]
    [New Thread 0x7fffe9bec700 (LWP 28021)]
    [New Thread 0x7fffe91e4700 (LWP 28022)]
    [New Thread 0x7fffe88d9700 (LWP 28025)]
    [New Thread 0x7fffe7d16700 (LWP 28035)]
    [Switching to Thread 0x7fffec224700 (LWP 28011)]
    
    Thread 3 "moar" hit Breakpoint 1, MVM_continuation_invoke (tc=0x61800029b080, cont=0x7fffe9268100, code=0x62300000e130, res_reg=0x6110046b6720) at src/core/continuation.c:151
    151	        MVM_exception_throw_adhoc(tc, "continuationinvoke expects an MVMContinuation");
    (gdb) bt
    #0  MVM_continuation_invoke (tc=0x61800029b080, cont=0x7fffe9268100, code=0x62300000e130, res_reg=0x6110046b6720) at src/core/continuation.c:151
    #1  0x00007ffff5be574c in MVM_interp_run (tc=0x61800029b080, initial_invoke=0x7ffff5c3f9d0 <thread_initial_invoke>, invoke_data=0x6020002b8230) at src/core/interp.c:3903
    #2  0x00007ffff5c3fd3f in start_thread (data=0x6020002b8230) at src/core/threads.c:87
    #3  0x00007ffff4f196ba in start_thread (arg=0x7fffec224700) at pthread_create.c:333
    #4  0x00007ffff523641d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
    (gdb) info threads
      Id   Target Id         Frame 
      1    Thread 0x7ffff7fd9780 (LWP 27926) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
      2    Thread 0x7ffff209a700 (LWP 27933) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
    * 3    Thread 0x7fffec224700 (LWP 28011) "moar" MVM_continuation_invoke (tc=0x61800029b080, cont=0x7fffe9268100, code=0x62300000e130, res_reg=0x6110046b6720) at src/core/continuation.c:151
      4    Thread 0x7fffeba23700 (LWP 28012) "moar" 0x00007ffff51fb30d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
      5    Thread 0x7fffeb181700 (LWP 28015) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
      6    Thread 0x7fffea91f700 (LWP 28016) "moar" syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
      7    Thread 0x7fffe9bec700 (LWP 28021) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
      8    Thread 0x7fffe91e4700 (LWP 28022) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
      9    Thread 0x7fffe88d9700 (LWP 28025) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
      10   Thread 0x7fffe7d16700 (LWP 28035) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
    (gdb) l
    146	
    147	void MVM_continuation_invoke(MVMThreadContext *tc, MVMContinuation *cont,
    148	                             MVMObject *code, MVMRegister *res_reg) {
    149	    /* First of all do a repr id check */
    150	    if (REPR(cont)->ID != MVM_REPR_ID_MVMContinuation)
    151	        MVM_exception_throw_adhoc(tc, "continuationinvoke expects an MVMContinuation");
    152	
    153	    /* Ensure we are the only invoker of the continuation. */
    154	    if (!MVM_trycas(&(cont->body.invoked), 0, 1))
    155	        MVM_exception_throw_adhoc(tc, "This continuation has already been invoked");
    (gdb) p REPR(cont)->ID
    $1 = 5
    (gdb) p MVM_dump_p6opaque(tc, cont)
    Scalar.new(#`(from Scalar) $!descriptor=ContainerDescriptor.new(#`(from ContainerDescriptor) $!of=(Mu), $!name='$continuation', $!default=(Any), $!dynamic=0), $!value=(Any))
    $2 = void
    (gdb) p MVM_dump_backtrace(tc)
       at SETTING::src/core/ThreadPoolScheduler.pm6:153  (./CORE.setting.moarvm:)
     from SETTING::src/core/ThreadPoolScheduler.pm6:242  (./CORE.setting.moarvm:)
     from SETTING::src/core/ThreadPoolScheduler.pm6:241  (./CORE.setting.moarvm:)
     from SETTING::src/core/ThreadPoolScheduler.pm6:236  (./CORE.setting.moarvm:run-one)
     from SETTING::src/core/ThreadPoolScheduler.pm6:278  (./CORE.setting.moarvm:)
     from SETTING::src/core/Thread.pm6:54  (./CORE.setting.moarvm:THREAD-ENTRY)
    $3 = void
    (gdb)

**Comment by dogbert17** [comment]
Fixed by https://github.com/rakudo/rakudo/commit/98839c8022a7a1b9fc740ac187e3830017833df1
