### ISSUE TITLE
malloc error in t/04-nativecall/06-struct.t

### ISSUE THREAD

**Issue by MasterDuke17** [MoarVM/MoarVM#1062]
```
t/04-nativecall/06-struct.t ..................................... 
1..34
ok 1 - getting long
ok 2 - getting num
ok 3 - getting int8
ok 4 - getting num32
ok 5 - getting CArray and element
ok 6 - getting long from C-created struct
ok 7 - getting num from C-created struct
ok 8 - getting int8 from C-created struct
ok 9 - getting num32 from C-created struct
ok 10 - C-created array member, elem 1
ok 11 - C-created array member, elem 2
ok 12 - C-created array member, elem 3
ok 13 - field 1 from struct 1 in struct
ok 14 - field 2 from struct 1 in struct
ok 15 - field 1 from struct 2 in struct
ok 16 - field 2 from struct 2 in struct
ok 17 - CPointer object in struct
ok 18 - first string in struct
ok 19 - second string in struct
ok 20 - C-side values in struct
ok 21 - Setting a CArray struct element to type object passes a NULL to C
ok 22 - C-side values in struct struct
ok 23 - C-side strict values in struct
ok 24 - and the int after is 42
ok 25 - nested first is 101
ok 26 - nested second is 77
ok 27 - struct with inlined structs has correct size
    1..3
    ok 1 - 'class EmptyCStructTest is repr<CStruct> { };' died
    ok 2 - right exception type (Exception)
    ok 3 - .message matches -> ;; $_? is raw {  \#`(Block|140722506428248) ... }
ok 28 - did we throws-like Exception?
ok 29 - Can inline fixed sizes array (1)
moar(12380,0x7fffb3ce5340) malloc: *** error for object 0x7ffc7ff071d4: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Failed 5/34 subtests 
```

**Comment by MasterDuke17** [comment]
Caught something in gdb.
```
ok 29 - Can inline fixed sizes array (1)
free(): invalid pointer

Thread 1 "moar" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff75b7535 in __GI_abort () at abort.c:79
#2  0x00007ffff761e516 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7742c00 "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff76253aa in malloc_printerr (str=str@entry=0x7ffff7740d85 "free(): invalid pointer") at malloc.c:5336
#4  0x00007ffff76271fc in _int_free (av=<optimized out>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4143
#5  0x00007ffff79fb557 in MVM_free (p=<optimized out>) at src/core/alloc.h:40
#6  gc_cleanup (tc=<optimized out>, data=0x7ffff73b5330, st=<optimized out>) at src/6model/reprs/CArray.c:140
#7  gc_free (tc=<optimized out>, obj=0x7ffff73b5318) at src/6model/reprs/CArray.c:147
#8  0x00007ffff79c6895 in MVM_gc_collect_free_nursery_uncopied (tc=tc@entry=0x55555555aca0, limit=0x7ffff73d0ff8) at src/gc/collect.c:620
#9  0x00007ffff79c2084 in finish_gc (is_coordinator=<optimized out>, gen=<optimized out>, tc=0x55555555aca0) at src/gc/orchestrate.c:241
#10 run_gc (tc=tc@entry=0x55555555aca0, what_to_do=what_to_do@entry=0 '\000') at src/gc/orchestrate.c:413
#11 0x00007ffff79c29df in MVM_gc_enter_from_allocator (tc=tc@entry=0x55555555aca0) at src/gc/orchestrate.c:526
#12 0x00007ffff79c2d56 in MVM_gc_allocate_nursery (tc=0x55555555aca0, size=<optimized out>) at src/gc/allocation.c:35
#13 0x00007ffff79c2f6b in MVM_gc_allocate_object (tc=0x55555555aca0, st=<optimized out>) at src/gc/allocation.c:89
#14 0x00007ffff79d8a43 in MVM_repr_alloc_init (tc=tc@entry=0x55555555aca0, type=<optimized out>) at src/6model/reprconv.c:17
#15 0x00007ffff7980406 in MVM_exception_backtrace (tc=0x55555555aca0, ex_obj=<optimized out>) at src/core/exceptions.c:547
#16 0x00007ffff7983a3b in MVM_interp_run (tc=0x2, tc@entry=0x55555555aca0, initial_invoke=0x0, invoke_data=0x0) at src/core/interp.c:3860
#17 0x00007ffff7a87a95 in MVM_vm_run_file (instance=0x55555555a260, filename=<optimized out>) at src/moar.c:444
#18 0x0000555555555791 in main (argc=10, argv=0x7fffffffddc8) at src/main.c:302
(gdb) f 8
#8  0x00007ffff79c6895 in MVM_gc_collect_free_nursery_uncopied (tc=tc@entry=0x55555555aca0, limit=0x7ffff73d0ff8) at src/gc/collect.c:620
620                     REPR(obj)->gc_free(tc, obj);
(gdb) call MVM_dump_backtrace(tc)
   at SETTING::src/core/Backtrace.pm6:92  (./CORE.setting.moarvm:new)
 from SETTING::src/core/Failure.pm6:12  (./CORE.setting.moarvm:SET-SELF)
 from SETTING::src/core/Failure.pm6:25  (./CORE.setting.moarvm:new)
 from SETTING::src/core/Rakudo/Internals.pm6:1003  (./CORE.setting.moarvm:INITIALIZE-DYNAMIC)
 from SETTING::src/core/stubs.pm6:34  (./CORE.setting.moarvm:DYNAMIC)
 from /home/dan/Source/perl6/rakudo/lib/NativeCall.pm6 (NativeCall):312  (/home/dan/Source/perl6/rakudo/t/04-nativecall/.precomp/D23BE93F6D7566493365557E43665A6180E4025A/6B/6B7A1AECF02807F30DDAD99C02C34440CA036AF6:)
 from SETTING::src/core/Lock.pm6:25  (./CORE.setting.moarvm:protect)
 from /home/dan/Source/perl6/rakudo/lib/NativeCall.pm6 (NativeCall):272  (/home/dan/Source/perl6/rakudo/t/04-nativecall/.precomp/D23BE93F6D7566493365557E43665A6180E4025A/6B/6B7A1AECF02807F30DDAD99C02C34440CA036AF6:setup)
 from /home/dan/Source/perl6/rakudo/lib/NativeCall.pm6 (NativeCall):576  (/home/dan/Source/perl6/rakudo/t/04-nativecall/.precomp/D23BE93F6D7566493365557E43665A6180E4025A/6B/6B7A1AECF02807F30DDAD99C02C34440CA036AF6:CALL-ME)
 from gen/moar/BOOTSTRAP.nqp:3412  (./blib/Perl6/BOOTSTRAP.moarvm:)
 from t/04-nativecall/06-struct.t:201  (<ephemeral file>:<unit>)
 from t/04-nativecall/06-struct.t:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1684  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1888  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:1818  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:38  (blib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1773  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:48  (/home/dan/Source/perl6/rakudo/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:1  (/home/dan/Source/perl6/rakudo/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/dan/Source/perl6/rakudo/perl6.moarvm:<main>)
 from <unknown>:1  (/home/dan/Source/perl6/rakudo/perl6.moarvm:<entry>)
(gdb)
```

**Comment by dogbert17** [comment]
Here's valgrinds perspective:

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ MVM_JIT_DISABLE=1 ./perl6-valgrind-m -Ilib t/04-nativecall/06-struct.t
    ================================================================================================
    This is Rakudo Perl 6 running in valgrind, a tool for debugging and profiling programs.
    Running a program in valgrind usually takes *a lot* more time than running it directly,
    so please be patient.
    Valgrind options can be added with MVM_VALGRIND_OPTS environment variable.
    
    This Rakudo version is 2019.03.1.667.gd.4.ceb.97 built on MoarVM version 2019.05.96.gd.6.f.9.e.02,
    running on linuxmint (18.3.Sylvia) / linux (42.16.04.1.Ubuntu.SMP.Tue.Oct.10.16.32.20.UTC.2017)
    ------------------------------------------------------------------------------------------------
    ==9863== Memcheck, a memory error detector
    ==9863== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
    ==9863== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
    ==9863== Command: /home/dogbert/repos/rakudo/nqp/MoarVM/../../install/bin/moar --execname=/home/dogbert/repos/rakudo/perl6-valgrind-m --libpath=/home/dogbert/repos/rakudo --libpath=/home/dogbert/repos/rakudo/blib --libpath= --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib /home/dogbert/repos/rakudo/perl6.moarvm --nqp-lib=/home/dogbert/repos/rakudo/blib -Ilib t/04-nativecall/06-struct.t
    ==9863== 
    1..34
    ok 1 - getting long
    ok 2 - getting num
    ok 3 - getting int8
    ok 4 - getting num32
    ok 5 - getting CArray and element
    ok 6 - getting long from C-created struct
    ok 7 - getting num from C-created struct
    ok 8 - getting int8 from C-created struct
    ok 9 - getting num32 from C-created struct
    ok 10 - C-created array member, elem 1
    ok 11 - C-created array member, elem 2
    ok 12 - C-created array member, elem 3
    ok 13 - field 1 from struct 1 in struct
    ok 14 - field 2 from struct 1 in struct
    ok 15 - field 1 from struct 2 in struct
    ok 16 - field 2 from struct 2 in struct
    ok 17 - CPointer object in struct
    ok 18 - first string in struct
    ok 19 - second string in struct
    ok 20 - C-side values in struct
    ok 21 - Setting a CArray struct element to type object passes a NULL to C
    ok 22 - C-side values in struct struct
    ok 23 - C-side strict values in struct
    ok 24 - and the int after is 42
    ok 25 - nested first is 101
    ok 26 - nested second is 77
    ok 27 - struct with inlined structs has correct size
        1..3
        ok 1 - 'class EmptyCStructTest is repr<CStruct> { };' died
        ok 2 - right exception type (Exception)
        ok 3 - .message matches -> ;; $_? is raw {  \#`(Block|260966968) ... }
    ok 28 - did we throws-like Exception?
    ok 29 - Can inline fixed sizes array (1)
    ok 30 - Can inline fixed sizes array (2)
    ==9863== Thread 1:
    ==9863== Invalid free() / delete / delete[] / realloc()
    ==9863==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
    ==9863==    by 0x50D745A: MVM_free (alloc.h:40)
    ==9863==    by 0x50D7CBE: gc_cleanup (CArray.c:140)
    ==9863==    by 0x50D7D0D: gc_free (CArray.c:147)
    ==9863==    by 0x508E3BA: MVM_gc_collect_free_nursery_uncopied (collect.c:626)
    ==9863==    by 0x5086207: finish_gc (orchestrate.c:241)
    ==9863==    by 0x5086767: run_gc (orchestrate.c:418)
    ==9863==    by 0x5086BAE: MVM_gc_enter_from_allocator (orchestrate.c:531)
    ==9863==    by 0x508742A: MVM_gc_allocate_nursery (allocation.c:35)
    ==9863==    by 0x5017755: fastcreate (interp.c:72)
    ==9863==    by 0x5044B15: MVM_interp_run (interp.c:5924)
    ==9863==    by 0x519F327: MVM_vm_run_file (moar.c:444)
    ==9863==  Address 0x101b71d4 is 4 bytes inside a block of size 20 alloc'd
    ==9863==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
    ==9863==    by 0x50D9000: MVM_calloc (alloc.h:11)
    ==9863==    by 0x50DAA01: initialize (CStruct.c:409)
    ==9863==    by 0x5024A4E: MVM_interp_run (interp.c:1864)
    ==9863==    by 0x519F327: MVM_vm_run_file (moar.c:444)
    ==9863==    by 0x4016E6: main (main.c:302)
    ==9863== 
    ok 31 - Can inline fixed sizes array (3)
    ok 32 - Can inline fixed sizes array (4)
    ok 33 - Can inline fixed sizes array (5)
    ok 34 - Can inline fixed sizes array (6)
    ==9863== 
    ==9863== HEAP SUMMARY:
    ==9863==     in use at exit: 103,487,373 bytes in 299,385 blocks
    ==9863==   total heap usage: 959,514 allocs, 660,130 frees, 599,062,213 bytes allocated
    ==9863== 
    ==9863== LEAK SUMMARY:
    ==9863==    definitely lost: 384 bytes in 4 blocks
    ==9863==    indirectly lost: 64 bytes in 1 blocks
    ==9863==      possibly lost: 444,560 bytes in 7,927 blocks
    ==9863==    still reachable: 103,042,365 bytes in 291,453 blocks
    ==9863==         suppressed: 0 bytes in 0 blocks
    ==9863== Rerun with --leak-check=full to see details of leaked memory
    ==9863== 
    ==9863== For counts of detected and suppressed errors, rerun with: -v
    ==9863== ERROR SUMMARY: 20 errors from 2 contexts (suppressed: 0 from 0

**Comment by dogbert17** [comment]
There's a possibility that this behavior was introduced with commit https://github.com/MoarVM/MoarVM/commit/ac3d3c76954fa3c1b1db14ea999bf3248c2eda1c
