### ISSUE TITLE
Assertion error or SEGV when running t/spec/S04-phasers/in-loop.t

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#1112]
It seems as if commit https://github.com/MoarVM/MoarVM/commit/9ed86e4c95f929f2960e87c83ea009fe62bf366e has uncovered a bug which causes  t/spec/S04-phasers/in-loop.t to fail.

Under normal circumstances the bug is elusive and the test has to be run many times before the following shows up:

    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7ffff630b700 (LWP 19733)]
    WARNINGS for /home/dogbert/repos/rakudo/t/spec/S04-phasers/in-loop.rakudo.moar:
    Useless use of constant integer 42 in sink context (line 166)
    1..20
    not ok 1 - trait blocks work properly in for loop # TODO NEXT/LEAVE ordering RT #124952
    # Failed test 'trait blocks work properly in for loop'
    # at t/spec/S04-phasers/in-loop.rakudo.moar line 37
    # expected: '(1 F)(1 E)(1 a)(1 N)(1 Lv)(2 E)(2 a)(2 b)(2 N)(2 Lv)(3 E)(3 a)(3 N)(3 Lv)(4 E)(4 Lv)(4 Lst)'
    #      got: '(1 F)(1 E)(1 a)(1 N)(1 Lv)(2 E)(2 a)(2 b)(2 Lv)(2 N)(3 E)(3 a)(3 N)(3 Lv)(4 E)(4 Lv)(4 Lst)'
    not ok 2 - trait blocks work properly in for loop # TODO NEXT/LEAVE ordering RT #124952
    # Failed test 'trait blocks work properly in for loop'
    # at t/spec/S04-phasers/in-loop.rakudo.moar line 68
    # expected: '(1 F1)(1 F2)(1 E1)(1 E2)(1 a)(1 N2)(1 N1)(1 Lv2)(1 Lv1)(2 E1)(2 E2)(2 a)(2 b)(2 N2)(2 N1)(2 Lv2)(2 Lv1)(3 E1)(3 E2)(3 a)(3 N2)(3 N1)(3 Lv2)(3 Lv1)(4 E1)(4 E2)(4 Lv2)(4 Lv1)(4 Lst2)(4 Lst1)'
    #      got: '(1 F1)(1 F2)(1 E1)(1 E2)(1 a)(1 N2)(1 N1)(1 Lv2)(1 Lv1)(2 E1)(2 E2)(2 a)(2 b)(2 Lv2)(2 Lv1)(2 N2)(2 N1)(3 E1)(3 E2)(3 a)(3 N2)(3 N1)(3 Lv2)(3 Lv1)(4 E1)(4 E2)(4 Lv2)(4 Lv1)(4 Lst1)(4 Lst2)'
    ok 3 - LAST does not fire for empty loop
    ok 4 - "last" statement called by LEAVE breaks out of while loop
    ok 5 - LEAVE in while loop works as expected
    ok 6 - no UnwindException with "last" and "ENTER" in for loop
    ok 7 - LAST phaser without block does not put Mu in the iteration variable
    ok 8 - LAST phaser with    block does not put Mu in the iteration variable
    
    Thread 1 "moar" received signal SIGSEGV, Segmentation fault.
    p6takefirstflag (tc=0x604a60, cur_op=0x3d8dae6 "\004") at src/vm/moar/ops/perl6_ops.c:202
    202	    if (vm_code->header.flags & RAKUDO_FIRST_FLAG) {
    (gdb) bt
    #0  p6takefirstflag (tc=0x604a60, cur_op=0x3d8dae6 "\004") at src/vm/moar/ops/perl6_ops.c:202
    #1  0x00007ffff75f9aef in MVM_interp_run (tc=tc@entry=0x604a60, initial_invoke=0x7ffff1920598, invoke_data=0x0) at src/core/interp.c:6571
    #2  0x00007ffff76f72c4 in MVM_vm_run_file (instance=0x604010, filename=<optimized out>) at src/moar.c:444
    #3  0x000000000040120f in main (argc=10, argv=0x7fffffffddc8) at src/main.c:302
    (gdb) l
    197	static MVMuint8 s_p6takefirstflag[] = {
    198	    MVM_operand_int64 | MVM_operand_write_reg
    199	};
    200	static void p6takefirstflag(MVMThreadContext *tc, MVMuint8 *cur_op) {
    201	    MVMObject *vm_code = tc->cur_frame->code_ref;
    202	    if (vm_code->header.flags & RAKUDO_FIRST_FLAG) {
    203	        vm_code->header.flags ^= RAKUDO_FIRST_FLAG;
    204	        GET_REG(tc, 0).i64 = 1;
    205	    }
    206	    else {
    (gdb) p vm_code->header.flags
    Cannot access memory at address 0xc
    (gdb) p vm_code->header
    Cannot access memory at address 0x0
    (gdb) info threads
      Id   Target Id         Frame 
    * 1    Thread 0x7ffff7fdb700 (LWP 19732) "moar" p6takefirstflag (tc=0x604a60, cur_op=0x3d8dae6 "\004") at src/vm/moar/ops/perl6_ops.c:202
      2    Thread 0x7ffff630b700 (LWP 19733) "moar" __memcpy_sse2 () at ../sysdeps/x86_64/multiarch/../memcpy.S:441
    (gdb) p MVM_dump_backtrace(tc)
       at t/spec/S04-phasers/in-loop.rakudo.moar:132  (<ephemeral file>:)
     from SETTING::src/core/Any-iterable-methods.pm6:220  (/home/dogbert/repos/rakudo/CORE.setting.moarvm:sink-all)
     from SETTING::src/core/Seq.pm6:128  (/home/dogbert/repos/rakudo/CORE.setting.moarvm:sink)
     from t/spec/S04-phasers/in-loop.rakudo.moar:132  (<ephemeral file>:foo)
     from t/spec/S04-phasers/in-loop.rakudo.moar:136  (<ephemeral file>:)
     from SETTING::src/core/Any-iterable-methods.pm6:220  (/home/dogbert/repos/rakudo/CORE.setting.moarvm:sink-all)
     from SETTING::src/core/Seq.pm6:128  (/home/dogbert/repos/rakudo/CORE.setting.moarvm:sink)
     from t/spec/S04-phasers/in-loop.rakudo.moar:132  (<ephemeral file>:foo)
     from t/spec/S04-phasers/in-loop.rakudo.moar:139  (<ephemeral file>:)
     from t/spec/S04-phasers/in-loop.rakudo.moar:5  (<ephemeral file>:<unit>)
     from t/spec/S04-phasers/in-loop.rakudo.moar:1  (<ephemeral file>:<unit-outer>)
     from gen/moar/stage2/NQPHLL.nqp:1753  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:eval)
     from gen/moar/stage2/NQPHLL.nqp:1957  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
     from gen/moar/stage2/NQPHLL.nqp:1887  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
     from src/Perl6/Compiler.nqp:44  (/home/dogbert/repos/rakudo/blib/Perl6/Compiler.moarvm:command_eval)
     from gen/moar/stage2/NQPHLL.nqp:1842  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_line)
     from gen/moar/main.nqp:82  (/home/dogbert/repos/rakudo/perl6.moarvm:MAIN)
     from gen/moar/main.nqp:47  (/home/dogbert/repos/rakudo/perl6.moarvm:<mainline>)
     from <unknown>:1  (/home/dogbert/repos/rakudo/perl6.moarvm:<main>)
     from <unknown>:1  (/home/dogbert/repos/rakudo/perl6.moarvm:<entry>)
    $1 = 

If however MoarVM is built with --no-optimize the following error crops up regularly:

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6-gdb-m -Ilib t/spec/S04-phasers/in-loop.rakudo.moar
    ================================================================================================
    This is Rakudo Perl 6 running in the  debugger, which often allows the user to generate useful back-
    traces to debug or report issues in Rakudo, the MoarVM backend or the currently running code.
    
    This Rakudo version is 2019.03.1.566.g.45.bcff.8 built on MoarVM version 2019.05.36.ge.865.f.43,
    running on linuxmint (18.3.Sylvia) / linux (42.16.04.1.Ubuntu.SMP.Tue.Oct.10.16.32.20.UTC.2017)
    
    Type `bt full` to generate a backtrace if applicable, type `q` to quit or `help` for help.
    ------------------------------------------------------------------------------------------------
    Reading symbols from /home/dogbert/repos/rakudo/nqp/MoarVM/../../install/bin/moar...done.
    Starting program: /home/dogbert/repos/rakudo/install/bin/moar --execname=/home/dogbert/repos/rakudo/perl6-gdb-m --libpath=/home/dogbert/repos/rakudo --libpath=/home/dogbert/repos/rakudo/blib --libpath= --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib /home/dogbert/repos/rakudo/perl6.moarvm --nqp-lib=/home/dogbert/repos/rakudo/blib -Ilib t/spec/S04-phasers/in-loop.rakudo.moar
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7ffff6222700 (LWP 20926)]
    WARNINGS for /home/dogbert/repos/rakudo/t/spec/S04-phasers/in-loop.rakudo.moar:
    Useless use of constant integer 42 in sink context (line 166)
    1..20
    not ok 1 - trait blocks work properly in for loop # TODO NEXT/LEAVE ordering RT #124952
    # Failed test 'trait blocks work properly in for loop'
    # at t/spec/S04-phasers/in-loop.rakudo.moar line 37
    # expected: '(1 F)(1 E)(1 a)(1 N)(1 Lv)(2 E)(2 a)(2 b)(2 N)(2 Lv)(3 E)(3 a)(3 N)(3 Lv)(4 E)(4 Lv)(4 Lst)'
    #      got: '(1 F)(1 E)(1 a)(1 N)(1 Lv)(2 E)(2 a)(2 b)(2 Lv)(2 N)(3 E)(3 a)(3 N)(3 Lv)(4 E)(4 Lv)(4 Lst)'
    not ok 2 - trait blocks work properly in for loop # TODO NEXT/LEAVE ordering RT #124952
    # Failed test 'trait blocks work properly in for loop'
    # at t/spec/S04-phasers/in-loop.rakudo.moar line 68
    # expected: '(1 F1)(1 F2)(1 E1)(1 E2)(1 a)(1 N2)(1 N1)(1 Lv2)(1 Lv1)(2 E1)(2 E2)(2 a)(2 b)(2 N2)(2 N1)(2 Lv2)(2 Lv1)(3 E1)(3 E2)(3 a)(3 N2)(3 N1)(3 Lv2)(3 Lv1)(4 E1)(4 E2)(4 Lv2)(4 Lv1)(4 Lst2)(4 Lst1)'
    #      got: '(1 F1)(1 F2)(1 E1)(1 E2)(1 a)(1 N2)(1 N1)(1 Lv2)(1 Lv1)(2 E1)(2 E2)(2 a)(2 b)(2 Lv2)(2 Lv1)(2 N2)(2 N1)(3 E1)(3 E2)(3 a)(3 N2)(3 N1)(3 Lv2)(3 Lv1)(4 E1)(4 E2)(4 Lv2)(4 Lv1)(4 Lst1)(4 Lst2)'
    ok 3 - LAST does not fire for empty loop
    ok 4 - "last" statement called by LEAVE breaks out of while loop
    ok 5 - LEAVE in while loop works as expected
    ok 6 - no UnwindException with "last" and "ENTER" in for loop
    ok 7 - LAST phaser without block does not put Mu in the iteration variable
    ok 8 - LAST phaser with    block does not put Mu in the iteration variable
    moar: src/gc/collect.c:589: MVM_gc_collect_free_nursery_uncopied: Assertion `item->sc_forward_u.forwarder != NULL' failed.
    
    Thread 1 "moar" received signal SIGABRT, Aborted.
    0x00007ffff6f8b428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
    54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    (gdb) bt
    #0  0x00007ffff6f8b428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
    #1  0x00007ffff6f8d02a in __GI_abort () at abort.c:89
    #2  0x00007ffff6f83bd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7ffff76e9540 "item->sc_forward_u.forwarder != NULL", file=file@entry=0x7ffff76e93e1 "src/gc/collect.c", 
        line=line@entry=589, function=function@entry=0x7ffff76e9600 <__PRETTY_FUNCTION__.17209> "MVM_gc_collect_free_nursery_uncopied") at assert.c:92
    #3  0x00007ffff6f83c82 in __GI___assert_fail (assertion=0x7ffff76e9540 "item->sc_forward_u.forwarder != NULL", file=0x7ffff76e93e1 "src/gc/collect.c", line=589, 
        function=0x7ffff76e9600 <__PRETTY_FUNCTION__.17209> "MVM_gc_collect_free_nursery_uncopied") at assert.c:101
    #4  0x00007ffff7573c52 in MVM_gc_collect_free_nursery_uncopied (executing_thread=0x604a60, tc=0x604a60, limit=0x7ffff6622ff0) at src/gc/collect.c:589
    #5  0x00007ffff756bbc8 in finish_gc (tc=0x604a60, gen=0 '\000', is_coordinator=1 '\001') at src/gc/orchestrate.c:241
    #6  0x00007ffff756c128 in run_gc (tc=0x604a60, what_to_do=0 '\000') at src/gc/orchestrate.c:418
    #7  0x00007ffff756c56f in MVM_gc_enter_from_allocator (tc=0x604a60) at src/gc/orchestrate.c:531
    #8  0x00007ffff756cdeb in MVM_gc_allocate_nursery (tc=0x604a60, size=32) at src/gc/allocation.c:35
    #9  0x00007ffff756cbe6 in MVM_gc_allocate (tc=0x604a60, size=32) at src/gc/allocation.h:18
    #10 0x00007ffff756ce74 in MVM_gc_allocate_zeroed (tc=0x604a60, size=32) at src/gc/allocation.c:52
    #11 0x00007ffff756d03b in MVM_gc_allocate_object (tc=0x604a60, st=0x66d9b8) at src/gc/allocation.c:89
    #12 0x00007ffff74f7a78 in MVM_args_slurpy_named (tc=0x604a60, ctx=0x7ffff7fb9360) at src/core/args.c:673
    #13 0x00007ffff7505489 in MVM_interp_run (tc=0x604a60, initial_invoke=0x7ffff7680a7b <toplevel_initial_invoke>, invoke_data=0x6a1068) at src/core/interp.c:1208
    #14 0x00007ffff7680be0 in MVM_vm_run_file (instance=0x604010, filename=0x7fffffffe245 "/home/dogbert/repos/rakudo/perl6.moarvm") at src/moar.c:444
    #15 0x00000000004016e7 in main (argc=10, argv=0x7fffffffddc8) at src/main.c:302
    (gdb) info threads
      Id   Target Id         Frame 
    * 1    Thread 0x7ffff7fdb700 (LWP 20922) "moar" 0x00007ffff6f8b428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
      2    Thread 0x7ffff6222700 (LWP 20926) "moar" 0x00007ffff75f1e1e in write_instructions (tc=0x68eac0, g=0x7fffec2f0470, ws=0x7fffec20ac60, bb=0x7fffec5af470) at src/spesh/codegen.c:162
    (gdb) f 4 
    #4  0x00007ffff7573c52 in MVM_gc_collect_free_nursery_uncopied (executing_thread=0x604a60, tc=0x604a60, limit=0x7ffff6622ff0) at src/gc/collect.c:589
    589	            assert(item->sc_forward_u.forwarder != NULL);
    (gdb) p MVM_dump_backtrace(tc)
       at SETTING::src/core/Rakudo/Iterator.pm6:1868  (/home/dogbert/repos/rakudo/CORE.setting.moarvm:SET-SELF)
     from SETTING::src/core/Rakudo/Iterator.pm6:1879  (/home/dogbert/repos/rakudo/CORE.setting.moarvm:new)
     from SETTING::src/core/Rakudo/Iterator.pm6:1924  (/home/dogbert/repos/rakudo/CORE.setting.moarvm:IntRange)
     from SETTING::src/core/Range.pm6:128  (/home/dogbert/repos/rakudo/CORE.setting.moarvm:iterator)
     from SETTING::src/core/Any-iterable-methods.pm6:40  (/home/dogbert/repos/rakudo/CORE.setting.moarvm:map)
     from t/spec/S04-phasers/in-loop.rakudo.moar:132  (<ephemeral file>:foo)
     from t/spec/S04-phasers/in-loop.rakudo.moar:136  (<ephemeral file>:)
     from SETTING::src/core/Any-iterable-methods.pm6:220  (/home/dogbert/repos/rakudo/CORE.setting.moarvm:sink-all)
     from SETTING::src/core/Seq.pm6:128  (/home/dogbert/repos/rakudo/CORE.setting.moarvm:sink)
     from t/spec/S04-phasers/in-loop.rakudo.moar:132  (<ephemeral file>:foo)
     from t/spec/S04-phasers/in-loop.rakudo.moar:136  (<ephemeral file>:)
     from SETTING::src/core/Any-iterable-methods.pm6:220  (/home/dogbert/repos/rakudo/CORE.setting.moarvm:sink-all)
     from SETTING::src/core/Seq.pm6:128  (/home/dogbert/repos/rakudo/CORE.setting.moarvm:sink)
     from t/spec/S04-phasers/in-loop.rakudo.moar:132  (<ephemeral file>:foo)
     from t/spec/S04-phasers/in-loop.rakudo.moar:136  (<ephemeral file>:)
     from SETTING::src/core/Any-iterable-methods.pm6:220  (/home/dogbert/repos/rakudo/CORE.setting.moarvm:sink-all)
     from SETTING::src/core/Seq.pm6:128  (/home/dogbert/repos/rakudo/CORE.setting.moarvm:sink)
     from t/spec/S04-phasers/in-loop.rakudo.moar:132  (<ephemeral file>:foo)
     from t/spec/S04-phasers/in-loop.rakudo.moar:139  (<ephemeral file>:)
     from t/spec/S04-phasers/in-loop.rakudo.moar:5  (<ephemeral file>:<unit>)
     from t/spec/S04-phasers/in-loop.rakudo.moar:1  (<ephemeral file>:<unit-outer>)
     from gen/moar/stage2/NQPHLL.nqp:1753  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:eval)
     from gen/moar/stage2/NQPHLL.nqp:1957  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
     from gen/moar/stage2/NQPHLL.nqp:1887  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
     from src/Perl6/Compiler.nqp:44  (/home/dogbert/repos/rakudo/blib/Perl6/Compiler.moarvm:command_eval)
     from gen/moar/stage2/NQPHLL.nqp:1842  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_line)
     from gen/moar/main.nqp:82  (/home/dogbert/repos/rakudo/perl6.moarvm:MAIN)
     from gen/moar/main.nqp:47  (/home/dogbert/repos/rakudo/perl6.moarvm:<mainline>)
     from <unknown>:1  (/home/dogbert/repos/rakudo/perl6.moarvm:<main>)
     from <unknown>:1  (/home/dogbert/repos/rakudo/perl6.moarvm:<entry>)
    $1 = void
    (gdb) 

It looks as if the problem vanishes if it is run with MVM_SPESH_INLINE_DISABLE=1

**Comment by dogbert17** [comment]
Fixed with commit https://github.com/rakudo/rakudo/commit/bd2ceefd5cb4ee9f0cd43b332fdffdc78dcfc645
