### ISSUE TITLE
moar in realloc(): error: bogus pointer (double free?)

### ISSUE THREAD

**Issue by FROGGS** [MoarVM/MoarVM#118]
gist: https://gist.github.com/carbin/ebb5c4eb0aedfaf5839c

```bash
#3 0x0000198ca4040621 in realloc (ptr=0x198cad537dc0, size=128)
at /usr/src/lib/libc/stdlib/malloc.c:1271
r = (void *) 0x0
saved_errno = 0
#4 0x0000198ca620bd7c in set_size_internal (tc=0x198cae71f400,
body=0x198ca4b82450, n=9, repr_data=0x198caf42ccc0)
at src/6model/reprs/MVMArray.c:325
elems = 1
---Type <return> to continue, or q <return> to quit---
start = 0
ssize = 16
slots = (void *) 0x198cad537dc0
#5 0x0000198ca620cd9c in unshift (tc=0x198cae71f400, st=0x198cadcea1c0,
root=0x198ca4b82438, data=0x198ca4b82450, value=
{o = 0x198ca4b814c8, s = 0x198ca4b814c8, i8 = -56 '�', ui8 = 200 '�', i16 = 5320, ui16 = 5320, i32 = -1531439928, ui32 = 2763527368, i64 = 28091849643208, ui64 = 28091849643208, n32 = -7.98324847e-17, n64 = 1.3879217836846752e-310},
kind=8) at src/6model/reprs/MVMArray.c:599
n = 8
elems = 1
i = 28092012819456
repr_data = (MVMArrayREPRData *) 0x198caf42ccc0
body = (MVMArrayBody *) 0x198ca4b82450
```

**Comment by jnthn** [comment]
So if it's fixed, we can close it. :-)
