### ISSUE TITLE
Explosive memory growth in spesh guards when creating lots of variables in rakudo

### ISSUE THREAD

**Issue by MasterDuke17** [MoarVM/MoarVM#1223]
I created a script that declares 60k unique variables:
`perl6 -e 'say "my \$x$_ = $_;" for ^60_000' >60k.p6`
When I run that (`perl6 --stagestats 60k.p6`) it takes about 30s to get to printing a time for stage 'moar', and then it just sits and after a couples seconds memory use increases rapidly (>20gb before I kill it). I printed out `result->body.num_positions` in `update_state()` in src/spesh/plugin.c. At first there are a couple small numbers, bouncing back and forth with values between 1 and 9, then eventually it starts at 1 and increments to 6865 (or beyond, depending on whether spesh is disabled or not). `update_state()` runs a loop up to `result->body.num_positions` and calls `copy_guard_set()`, where heaptrack says all the allocating occurs.

**Comment by coke** [comment]
Tried on v2021.10-23-gc50bc9985. on mac os 11.6 and got:

```
 $ raku --stagestats 60k.p6
Stage start      :   0.001
Stage parse      :  81.250
Stage syntaxcheck:   0.000
Stage ast        :   0.000
Stage optimize   :   9.285
Stage mast       :  14.589
Stage mbc        :   0.843
Stage moar       :   0.000
Segmentation fault: 11
```
```

**Comment by MasterDuke17** [comment]
```
[dan@alexandria perl6]$ gdb --args ./install/bin/raku 60k_unique_variables.raku 
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./install/bin/raku...
(gdb) r
Starting program: /home/dan/Source/perl6/install/bin/raku 60k_unique_variables.raku
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff6d9e640 (LWP 452770)]

Thread 1 "raku" received signal SIGSEGV, Segmentation fault.
0x00007ffff758ea08 in __memset_avx2_unaligned_erms () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff758ea08 in __memset_avx2_unaligned_erms () from /usr/lib/libc.so.6
#1  0x00007ffff785f921 in allocate_frame (tc=tc@entry=0x55555555a120, static_frame=<optimized out>, spesh_cand=<optimized out>, spesh_cand@entry=0x0, heap=heap@entry=0) at src/core/frame.c:286
#2  0x00007ffff785feac in MVM_frame_dispatch (tc=tc@entry=0x55555555a120, code=<optimized out>, args=..., spesh_cand=spesh_cand@entry=-1) at src/core/frame.c:535
#3  0x00007ffff78edbac in MVM_disp_program_record_end (tc=tc@entry=0x55555555a120, record=record@entry=0x7ffff7616178, thunked=0x0) at src/disp/program.c:2840
#4  0x00007ffff7865b9b in handle_end_of_dispatch_record (thunked=<optimized out>, tc=0x55555555a120) at src/core/callstack.c:541
#5  MVM_callstack_unwind_dispatch_record (tc=0x55555555a120, thunked=thunked@entry=0x0) at src/core/callstack.c:696
#6  0x00007ffff78e3712 in run_dispatch (tc=<optimized out>, record=record@entry=0x7ffff7616178, disp=<optimized out>, capture=<optimized out>, thunked=thunked@entry=0x0) at src/disp/program.c:526
#7  0x00007ffff78edcdf in MVM_disp_program_record_end (tc=tc@entry=0x55555555a120, record=record@entry=0x7ffff7616178, thunked=0x0) at src/disp/program.c:2762
#8  0x00007ffff7865b9b in handle_end_of_dispatch_record (thunked=<optimized out>, tc=0x55555555a120) at src/core/callstack.c:541
#9  MVM_callstack_unwind_dispatch_record (tc=tc@entry=0x55555555a120, thunked=thunked@entry=0x0) at src/core/callstack.c:696
#10 0x00007ffff78e3712 in run_dispatch (tc=tc@entry=0x55555555a120, record=record@entry=0x7ffff7616178, disp=disp@entry=0x555555573820, capture=capture@entry=0x7ffff6f96f28, thunked=thunked@entry=0x0) at src/disp/program.c:526
#11 0x00007ffff78e7327 in MVM_disp_program_run_dispatch (tc=0x55555555a120, disp=0x555555573820, arg_info=..., ic_entry_ptr=<optimized out>, ic_entry=<optimized out>, update_sf=<optimized out>) at src/disp/program.c:598
#12 0x00007ffff7850156 in MVM_interp_run (tc=0x7ffff761b6f8, initial_invoke=0x0, initial_invoke@entry=0x7ffff7969b90 <toplevel_initial_invoke>, invoke_data=0x0, invoke_data@entry=0x7ffff7969b90 <toplevel_initial_invoke>, 
    outer_runloop=0x7ffff761b700, outer_runloop@entry=0x0) at src/core/interp.c:5433
#13 0x00007ffff796aca5 in MVM_vm_run_file (instance=instance@entry=0x555555559590, filename=filename@entry=0x555555559520 "/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm") at src/moar.c:505
#14 0x00005555555557d8 in main (argc=<optimized out>, argv=0x7fffffffe338) at src/vm/moar/runner/main.c:474
(gdb)
```

**Comment by MasterDuke17** [comment]
Tests added in https://github.com/Raku/roast/pull/771, so closing this.
