### ISSUE TITLE
SEGV when profiling a script with some combination of fail/try

### ISSUE THREAD

**Issue by MasterDuke17** [MoarVM/MoarVM#1463]
```
[dan@alexandria perl6]$ gdb --args ./install/bin/raku --profile=fail.html -e 'sub a() { for ^1_000 { fail("bye") if $_ %% 888 } }; try a for ^50_000'
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./install/bin/raku...
(gdb) r
Starting program: /home/dan/Source/perl6/install/bin/raku --profile=fail.html -e sub\ a\(\)\ \{\ for\ \^1_000\ \{\ fail\(\"bye\"\)\ if\ \$_\ %%\ 888\ \}\ \}\;\ try\ a\ for\ \^50_000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff6de3640 (LWP 1589037)]
Writing profiler output to fail.html
[Thread 0x7ffff6de3640 (LWP 1589037) exited]
[Inferior 1 (process 1589033) exited normally]
(gdb) r
Starting program: /home/dan/Source/perl6/install/bin/raku --profile=fail.html -e sub\ a\(\)\ \{\ for\ \^1_000\ \{\ fail\(\"bye\"\)\ if\ \$_\ %%\ 888\ \}\ \}\;\ try\ a\ for\ \^50_000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff6de3640 (LWP 1589196)]
Writing profiler output to fail.html

Thread 1 "raku" received signal SIGSEGV, Segmentation fault.
MVM_interp_run (tc=0x55555555a0d0, initial_invoke=0x0, initial_invoke@entry=0x7ffff79a0bf0 <toplevel_initial_invoke>, invoke_data=0x0, invoke_data@entry=0x7ffff79a0bf0 <toplevel_initial_invoke>, outer_runloop=0x22, outer_runloop@entry=0x0)
    at src/core/interp.c:2237
2237                    if (IS_CONCRETE(obj))
(gdb) bt
#0  MVM_interp_run (tc=0x55555555a0d0, initial_invoke=0x0, initial_invoke@entry=0x7ffff79a0bf0 <toplevel_initial_invoke>, invoke_data=0x0, invoke_data@entry=0x7ffff79a0bf0 <toplevel_initial_invoke>, outer_runloop=0x22, 
    outer_runloop@entry=0x0) at src/core/interp.c:2237
#1  0x00007ffff79a1d54 in MVM_vm_run_file (instance=instance@entry=0x555555559590, filename=filename@entry=0x555555559520 "/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm") at src/moar.c:504
#2  0x00005555555557c4 in main (argc=<optimized out>, argv=0x7fffffffe368) at src/vm/moar/runner/main.c:472
(gdb) call MVM_dump_backtrace(tc)
   at gen/moar/stage2/NQPHLL.nqp:680  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:dump_instrumented_profile_data)
 from gen/moar/stage2/NQPHLL.nqp:187  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:dump_profile_data)
 from gen/moar/stage2/NQPHLL.nqp:173  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:)
 from :1772  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from :1770  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from :1779  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from :1766  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from :30  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:protect)
 from :26  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:protect)
 from :1765  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from :1764  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from gen/moar/rakudo.nqp:136  (/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm:)
 from gen/moar/rakudo.nqp:127  (/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/rakudo.nqp:1  (/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm:<entry>)
(gdb) call MVM_dump_bytecode(tc)
00000      getcode            loc_47_obj, Frame_40
00001      takeclosure        loc_47_obj, loc_47_obj
00002      getcode            loc_45_obj, Frame_39
00003      takeclosure        loc_45_obj, loc_45_obj
00004      getcode            loc_14_obj, Frame_34
00005      takeclosure        loc_14_obj, loc_14_obj
00006      getcode            loc_13_obj, Frame_33
00007      takeclosure        loc_13_obj, loc_13_obj
00008      getcode            loc_12_obj, Frame_32
00009      takeclosure        loc_12_obj, loc_12_obj
00010      getcode            loc_11_obj, Frame_31
00011      takeclosure        loc_11_obj, loc_11_obj
00012      getcode            loc_10_obj, Frame_27
00013      takeclosure        loc_10_obj, loc_10_obj
00014      getcode            loc_9_obj, Frame_24
00015      takeclosure        loc_9_obj, loc_9_obj
00016      checkarity         3, 3
00017      param_rp_o         loc_0_obj, 0
00018      param_rp_o         loc_1_obj, 1
00019      param_rp_o         loc_2_obj, 2
00020      paramnamesused     
00021      wval               loc_3_obj, 1, 44
00022      bindlex            lex_Frame_23_lex1_obj, loc_3_obj
00023      wval               loc_6_obj, 1, 44
00024      bindlex            lex_Frame_23_lex2_obj, loc_6_obj
00025      wval               loc_7_obj, 1, 44
00026      bindlex            lex_Frame_23_lex3_obj, loc_7_obj
00027      wval               loc_8_obj, 1, 44
00028      bindlex            lex_Frame_23_lex4_obj, loc_8_obj
00029      bindlex            lex_Frame_23_lex10_obj, loc_9_obj
00030      bindlex            lex_Frame_23_lex11_obj, loc_10_obj
00031      bindlex            lex_Frame_23_lex12_obj, loc_11_obj
00032      bindlex            lex_Frame_23_lex13_obj, loc_12_obj
00033      bindlex            lex_Frame_23_lex14_obj, loc_13_obj
00034      bindlex            lex_Frame_23_lex15_obj, loc_14_obj
00035      hlllist            loc_16_obj
00036      create             loc_16_obj, loc_16_obj
00037      set                loc_15_obj, loc_16_obj
00038      const_s            loc_18_str, ''
00039      set                loc_17_str, loc_18_str
     annotation: gen/moar/stage2/NQPHLL.nqp:198
00040      bootstrarray       loc_16_obj
00041      create             loc_16_obj, loc_16_obj
00042      bindlex            lex_Frame_23_lex0_obj, loc_16_obj
00043      decont             loc_19_obj, loc_2_obj
00044      isconcrete         loc_20_int, loc_19_obj
00045      if_i               loc_20_int, label_1(00055)
     annotation: gen/moar/stage2/NQPHLL.nqp:201
00046      const_s            loc_18_str, 'profile-'
00047      time               loc_21_uint
00048      coerce_us          loc_22_str, loc_21_uint
00049      concat_s           loc_22_str, loc_18_str, loc_22_str
00050      const_s            loc_18_str, '.html'
00051      concat_s           loc_18_str, loc_22_str, loc_18_str
00052      hllboxtype_s       loc_19_obj
00053      box_s              loc_19_obj, loc_18_str, loc_19_obj
00054      set                loc_2_obj, loc_19_obj
     label_1:
00055      getlex_no          loc_19_obj, '&note'
00056      decont             loc_19_obj, loc_19_obj
00057      const_s            loc_18_str, 'Writing profiler output to '
00058      decont             loc_23_obj, loc_2_obj
00059      smrt_strify        loc_22_str, loc_23_obj
00060      concat_s           loc_22_str, loc_18_str, loc_22_str
00061      prepargs           Callsite_12
00062      arg_s              0, loc_22_str
00063      invoke_v           loc_19_obj
00064   -> decont             loc_19_obj, loc_2_obj
00065      smrt_strify        loc_22_str, loc_19_obj
00066      const_s            loc_18_str, '.json'
00067      const_i64_16       loc_20_int, -5
00068      eqat_s             loc_20_int, loc_22_str, loc_18_str, loc_20_int
00069      hllboxtype_i       loc_19_obj
00070      box_i              loc_19_obj, loc_20_int, loc_19_obj
00071      set                loc_4_obj, loc_19_obj
00072      decont             loc_19_obj, loc_2_obj
00073      smrt_strify        loc_18_str, loc_19_obj
00074      const_s            loc_22_str, '.sql'
00075      const_i64_16       loc_20_int, -4
00076      eqat_s             loc_20_int, loc_18_str, loc_22_str, loc_20_int
00077      hllboxtype_i       loc_19_obj
00078      box_i              loc_19_obj, loc_20_int, loc_19_obj
00079      set                loc_5_obj, loc_19_obj
00080      decont             loc_27_obj, loc_4_obj
00081      unless_o           loc_27_obj, label_2(00091)
     annotation: gen/moar/stage2/NQPHLL.nqp:212
00082      const_s            loc_22_str, '\\'
00083      hllboxtype_s       loc_19_obj
00084      box_s              loc_19_obj, loc_22_str, loc_19_obj
00085      bindlex            lex_Frame_23_lex2_obj, loc_19_obj
00086      const_s            loc_22_str, '\"'
00087      hllboxtype_s       loc_23_obj
00088      box_s              loc_23_obj, loc_22_str, loc_23_obj
00089      bindlex            lex_Frame_23_lex3_obj, loc_23_obj
00090      goto               label_3(00103)
     annotation: gen/moar/stage2/NQPHLL.nqp:217
     label_2:
00091      const_s            loc_22_str, '\\\\'
00092      hllboxtype_s       loc_24_obj
00093      box_s              loc_24_obj, loc_22_str, loc_24_obj
00094      bindlex            lex_Frame_23_lex2_obj, loc_24_obj
00095      const_s            loc_22_str, '\\"'
00096      hllboxtype_s       loc_25_obj
00097      box_s              loc_25_obj, loc_22_str, loc_25_obj
00098      bindlex            lex_Frame_23_lex3_obj, loc_25_obj
00099      const_s            loc_22_str, '\''
00100      hllboxtype_s       loc_26_obj
00101      box_s              loc_26_obj, loc_22_str, loc_26_obj
00102      bindlex            lex_Frame_23_lex4_obj, loc_26_obj
     label_3:
00103      const_i64_16       loc_20_int, -1
00104      bindlex            lex_Frame_23_lex5_int, loc_20_int
00105      hllhash            loc_27_obj
00106      create             loc_27_obj, loc_27_obj
00107      bindlex            lex_Frame_23_lex6_obj, loc_27_obj
00108      hllhash            loc_28_obj
00109      create             loc_28_obj, loc_28_obj
00110      bindlex            lex_Frame_23_lex7_obj, loc_28_obj
00111      hllhash            loc_29_obj
00112      create             loc_29_obj, loc_29_obj
00113      bindlex            lex_Frame_23_lex8_obj, loc_29_obj
00114      const_i64_16       loc_30_int, -1
00115      bindlex            lex_Frame_23_lex9_int, loc_30_int
     annotation: gen/moar/stage2/NQPHLL.nqp:678
00116      shift_o            loc_32_obj, loc_1_obj
00117      set                loc_31_obj, loc_32_obj
00118      iter               loc_32_obj, loc_31_obj
00119      set                loc_33_obj, loc_32_obj
     label_4:
00120      decont             loc_32_obj, loc_33_obj
00121      unless_o           loc_32_obj, label_7(00137)
00122      osrpoint           
00123      shift_o            loc_32_obj, loc_33_obj
00124      set                loc_34_obj, loc_32_obj
     annotation: gen/moar/stage2/NQPHLL.nqp:680
00125      getlex             loc_32_obj, lex_Frame_23_lex8_obj
00126      const_i64_16       loc_35_int, 0
00127      atpos_o            loc_36_obj, loc_34_obj, loc_35_int
00128      ifnonnull          loc_36_obj, label_5(00132)
00129      wval               loc_38_obj, 1, 44
00130      set                loc_37_obj, loc_38_obj
00131      goto               label_6(00133)
     label_5:
00132      set                loc_37_obj, loc_36_obj
     label_6:
00133      decont             loc_37_obj, loc_37_obj
00134      smrt_strify        loc_22_str, loc_37_obj
00135      bindkey_o          loc_32_obj, loc_22_str, loc_34_obj
00136      goto               label_4(00120)
     label_7:
00137      iter               loc_32_obj, loc_1_obj
00138      set                loc_39_obj, loc_32_obj
     label_8:
00139      decont             loc_32_obj, loc_39_obj
00140      unless_o           loc_32_obj, label_12(00165)
00141      osrpoint           
00142      shift_o            loc_32_obj, loc_39_obj
00143      set                loc_40_obj, loc_32_obj
     annotation: gen/moar/stage2/NQPHLL.nqp:686
00144      const_s            loc_22_str, 'call_graph'
00145      existskey          loc_35_int, loc_40_obj, loc_22_str
00146      unless_i           loc_35_int, label_11(00159)
     annotation: gen/moar/stage2/NQPHLL.nqp:687
00147      getlex             loc_32_obj, lex_Frame_23_lex11_obj
00148      decont             loc_32_obj, loc_32_obj
00149      const_s            loc_22_str, 'call_graph'
00150      atkey_o            loc_37_obj, loc_40_obj, loc_22_str
00151      ifnonnull          loc_37_obj, label_9(00155)
00152      wval               loc_36_obj, 1, 44
00153      set                loc_38_obj, loc_36_obj
00154      goto               label_10(00156)
     label_9:
00155      set                loc_38_obj, loc_37_obj
     label_10:
00156      prepargs           Callsite_0
00157      arg_o              0, loc_38_obj
00158      invoke_v           loc_32_obj
     label_11:
00159      getlex             loc_32_obj, lex_Frame_23_lex12_obj
00160      decont             loc_32_obj, loc_32_obj
00161      prepargs           Callsite_0
00162      arg_o              0, loc_40_obj
00163      invoke_v           loc_32_obj
00164      goto               label_8(00139)
     label_12:
00165      getlex             loc_32_obj, lex_Frame_23_lex7_obj
00166      unshift_o          loc_1_obj, loc_32_obj
00167      decont             loc_38_obj, loc_4_obj
00168      isfalse            loc_35_int, loc_38_obj
00169      set                loc_42_int, loc_35_int
00170      unless_i           loc_35_int, label_13(00174)
00171      decont             loc_38_obj, loc_5_obj
00172      isfalse            loc_41_int, loc_38_obj
00173      set                loc_42_int, loc_41_int
     label_13:
00174      unless_i           loc_42_int, label_18(00265)
     annotation: gen/moar/stage2/NQPHLL.nqp:703
00175      const_s            loc_22_str, 'default'
00176      const_s            loc_18_str, 'SysConfig'
00177      gethllsym          loc_38_obj, loc_22_str, loc_18_str
00178      decont             loc_37_obj, loc_38_obj
00179      findmeth           loc_36_obj, loc_37_obj, 'nqp-home'
00180      prepargs           Callsite_0
00181      arg_o              0, loc_38_obj
00182      invoke_o           loc_36_obj, loc_36_obj
00183      decont             loc_36_obj, loc_36_obj
00184      smrt_strify        loc_18_str, loc_36_obj
00185      const_s            loc_22_str, '/lib/profiler/template.html'
00186      concat_s           loc_22_str, loc_18_str, loc_22_str
00187      hllboxtype_s       loc_36_obj
00188      box_s              loc_36_obj, loc_22_str, loc_36_obj
00189      set                loc_43_obj, loc_36_obj
00190      set                loc_44_obj, loc_45_obj
00191      getlex_no          loc_38_obj, '&slurp'
00192      decont             loc_38_obj, loc_38_obj
00193      const_s            loc_22_str, 'src/vm/moar/profiler/template.html'
00194      prepargs           Callsite_12
00195      arg_s              0, loc_22_str
00196      invoke_o           loc_38_obj, loc_38_obj
00197      set                loc_36_obj, loc_38_obj
00198      goto               label_14(00200)
00199      takehandlerresult  loc_36_obj
     label_14:
00200      decont             loc_36_obj, loc_36_obj
00201      smrt_strify        loc_22_str, loc_36_obj
00202      set                loc_17_str, loc_22_str
00203      if_s               loc_17_str, label_16(00216)
     annotation: gen/moar/stage2/NQPHLL.nqp:706
00204      set                loc_46_obj, loc_47_obj
00205      getlex_no          loc_38_obj, '&slurp'
00206      decont             loc_38_obj, loc_38_obj
00207      prepargs           Callsite_0
00208      arg_o              0, loc_43_obj
00209      invoke_o           loc_38_obj, loc_38_obj
00210      set                loc_36_obj, loc_38_obj
00211      goto               label_15(00213)
00212      takehandlerresult  loc_36_obj
     label_15:
00213      decont             loc_36_obj, loc_36_obj
00214      smrt_strify        loc_22_str, loc_36_obj
00215      set                loc_17_str, loc_22_str
     label_16:
00216      if_s               loc_17_str, label_18(00265)
     annotation: gen/moar/stage2/NQPHLL.nqp:709
00217      getlex_no          loc_36_obj, '&note'
00218      decont             loc_36_obj, loc_36_obj
00219      const_s            loc_22_str, 'Could not locate profiler/template.html; should have been at '
00220      decont             loc_38_obj, loc_43_obj
00221      smrt_strify        loc_18_str, loc_38_obj
00222      concat_s           loc_18_str, loc_22_str, loc_18_str
00223      const_s            loc_22_str, '; outputting sql data instead'
00224      concat_s           loc_22_str, loc_18_str, loc_22_str
00225      prepargs           Callsite_12
00226      arg_s              0, loc_22_str
00227      invoke_v           loc_36_obj
00228      const_i64_16       loc_41_int, 1
00229      hllboxtype_i       loc_36_obj
00230      box_i              loc_36_obj, loc_41_int, loc_36_obj
00231      set                loc_5_obj, loc_36_obj
00232      const_s            loc_22_str, '&literal_subst'
00233      getlexstatic_o     loc_36_obj, loc_22_str
00234      decont             loc_36_obj, loc_36_obj
00235      const_s            loc_22_str, '.html'
00236      const_s            loc_18_str, '.sql'
00237      prepargs           Callsite_14
00238      arg_o              0, loc_2_obj
00239      arg_s              1, loc_22_str
00240      arg_s              2, loc_18_str
00241      invoke_o           loc_36_obj, loc_36_obj
00242      set                loc_2_obj, loc_36_obj
00243      decont             loc_36_obj, loc_2_obj
00244      smrt_strify        loc_18_str, loc_36_obj
00245      const_s            loc_22_str, '.sql'
00246      const_i64_16       loc_41_int, -4
00247      eqat_s             loc_41_int, loc_18_str, loc_22_str, loc_41_int
00248      if_i               loc_41_int, label_17(00256)
     annotation: gen/moar/stage2/NQPHLL.nqp:713
00249      decont             loc_36_obj, loc_2_obj
00250      smrt_strify        loc_22_str, loc_36_obj
00251      const_s            loc_18_str, '.sql'
00252      concat_s           loc_18_str, loc_22_str, loc_18_str
00253      hllboxtype_s       loc_36_obj
00254      box_s              loc_36_obj, loc_18_str, loc_36_obj
00255      set                loc_2_obj, loc_36_obj
     label_17:
00256      getlex_no          loc_36_obj, '&note'
00257      decont             loc_36_obj, loc_36_obj
00258      const_s            loc_18_str, 'Writing profiler output to '
00259      decont             loc_38_obj, loc_2_obj
00260      smrt_strify        loc_22_str, loc_38_obj
00261      concat_s           loc_22_str, loc_18_str, loc_22_str
00262      prepargs           Callsite_12
00263      arg_s              0, loc_22_str
00264      invoke_v           loc_36_obj
     label_18:
00265      getlex_no          loc_36_obj, '&open'
00266      decont             loc_36_obj, loc_36_obj
00267      const_i64_16       loc_42_int, 1
00268      prepargs           Callsite_17
00269      arg_o              0, loc_2_obj
00270      argconst_s         1, 'w'
00271      arg_i              2, loc_42_int
00272      invoke_o           loc_36_obj, loc_36_obj
00273      bindlex            lex_Frame_23_lex1_obj, loc_36_obj
00274      decont             loc_61_obj, loc_4_obj
00275      unless_o           loc_61_obj, label_19(00292)
     annotation: gen/moar/stage2/NQPHLL.nqp:722
00276      getlex             loc_38_obj, lex_Frame_23_lex13_obj
00277      decont             loc_38_obj, loc_38_obj
00278      prepargs           Callsite_0
00279      arg_o              0, loc_1_obj
00280      invoke_v           loc_38_obj
00281      getlex             loc_38_obj, lex_Frame_23_lex1_obj
00282      const_s            loc_22_str, ''
00283      getlex             loc_37_obj, lex_Frame_23_lex0_obj
00284      join               loc_22_str, loc_22_str, loc_37_obj
00285      decont             loc_48_obj, loc_38_obj
00286      findmeth           loc_37_obj, loc_48_obj, 'print'
00287      prepargs           Callsite_1
00288      arg_o              0, loc_38_obj
00289      arg_s              1, loc_22_str
00290      invoke_o           loc_37_obj, loc_37_obj
00291      goto               label_25(00418)
     label_19:
00292      decont             loc_61_obj, loc_5_obj
00293      unless_o           loc_61_obj, label_20(00372)
     annotation: gen/moar/stage2/NQPHLL.nqp:726
00294      getlex             loc_38_obj, lex_Frame_23_lex1_obj
00295      const_s            loc_22_str, 'BEGIN;'
00296      decont             loc_49_obj, loc_38_obj
00297      findmeth           loc_48_obj, loc_49_obj, 'say'
00298      prepargs           Callsite_1
00299      arg_o              0, loc_38_obj
00300      arg_s              1, loc_22_str
00301      invoke_o           loc_48_obj, loc_48_obj
00302      getlex             loc_38_obj, lex_Frame_23_lex1_obj
00303      const_s            loc_22_str, 'CREATE TABLE types(id INTEGER PRIMARY KEY ASC, name TEXT, extra_info JSON, type_links JSON);'
00304      decont             loc_50_obj, loc_38_obj
00305      findmeth           loc_49_obj, loc_50_obj, 'say'
00306      prepargs           Callsite_1
00307      arg_o              0, loc_38_obj
00308      arg_s              1, loc_22_str
00309      invoke_o           loc_49_obj, loc_49_obj
00310      getlex             loc_38_obj, lex_Frame_23_lex1_obj
00311      const_s            loc_22_str, 'CREATE TABLE routines(id INTEGER PRIMARY KEY ASC, name TEXT, line INT, file TEXT);'
00312      decont             loc_51_obj, loc_38_obj
00313      findmeth           loc_50_obj, loc_51_obj, 'say'
00314      prepargs           Callsite_1
00315      arg_o              0, loc_38_obj
00316      arg_s              1, loc_22_str
00317      invoke_o           loc_50_obj, loc_50_obj
00318      getlex             loc_38_obj, lex_Frame_23_lex1_obj
00319      const_s            loc_22_str, 'CREATE TABLE gcs(time INT, retained_bytes INT, promoted_bytes INT, gen2_roots INT, stolen_gen2_roots INT, full INT, responsible INT, cleared_bytes INT, start_time INT, sequence_num INT, thread_id INT, PRIMARY KEY(sequence_num, thread_id));'
00320      decont             loc_52_obj, loc_38_obj
00321      findmeth           loc_51_obj, loc_52_obj, 'say'
00322      prepargs           Callsite_1
00323      arg_o              0, loc_38_obj
00324      arg_s              1, loc_22_str
00325      invoke_o           loc_51_obj, loc_51_obj
00326      getlex             loc_38_obj, lex_Frame_23_lex1_obj
00327      const_s            loc_22_str, 'CREATE TABLE calls(id INTEGER PRIMARY KEY ASC, parent_id INT, routine_id INT, osr INT, spesh_entries INT, jit_entries INT, inlined_entries INT, inclusive_time INT, exclusive_time INT, entries INT, deopt_one INT, deopt_all INT, rec_depth INT, first_entry_time INT, highest_child_id INT, FOREIGN KEY(routine_id) REFERENCES routines(id));'
00328      decont             loc_53_obj, loc_38_obj
00329      findmeth           loc_52_obj, loc_53_obj, 'say'
00330      prepargs           Callsite_1
00331      arg_o              0, loc_38_obj
00332      arg_s              1, loc_22_str
00333      invoke_o           loc_52_obj, loc_52_obj
00334      getlex             loc_38_obj, lex_Frame_23_lex1_obj
00335      const_s            loc_22_str, 'CREATE TABLE profile(total_time INT, spesh_time INT, thread_id INT, parent_thread_id INT, root_node INT, first_entry_time INT, FOREIGN KEY(root_node) REFERENCES calls(id));'
00336      decont             loc_54_obj, loc_38_obj
00337      findmeth           loc_53_obj, loc_54_obj, 'say'
00338      prepargs           Callsite_1
00339      arg_o              0, loc_38_obj
00340      arg_s              1, loc_22_str
00341      invoke_o           loc_53_obj, loc_53_obj
00342      getlex             loc_38_obj, lex_Frame_23_lex1_obj
00343      const_s            loc_22_str, 'CREATE TABLE allocations(call_id INT, type_id INT, spesh INT, jit INT, count INT, replaced INT, PRIMARY KEY(call_id, type_id), FOREIGN KEY(call_id) REFERENCES calls(id), FOREIGN KEY(type_id) REFERENCES types(id));'
00344      decont             loc_55_obj, loc_38_obj
00345      findmeth           loc_54_obj, loc_55_obj, 'say'
00346      prepargs           Callsite_1
00347      arg_o              0, loc_38_obj
00348      arg_s              1, loc_22_str
00349      invoke_o           loc_54_obj, loc_54_obj
00350      getlex             loc_38_obj, lex_Frame_23_lex1_obj
00351      const_s            loc_22_str, 'CREATE TABLE deallocations(gc_seq_num INT, gc_thread_id INT, type_id INT, nursery_fresh INT, nursery_seen INT, gen2 INT, PRIMARY KEY(gc_seq_num, gc_thread_id, type_id), FOREIGN KEY(gc_seq_num, gc_thread_id) REFERENCES gcs(sequence_num, thread_id), FOREIGN KEY(type_id) REFERENCES types(id));'
00352      decont             loc_56_obj, loc_38_obj
00353      findmeth           loc_55_obj, loc_56_obj, 'say'
00354      prepargs           Callsite_1
00355      arg_o              0, loc_38_obj
00356      arg_s              1, loc_22_str
00357      invoke_o           loc_55_obj, loc_55_obj
00358      getlex             loc_38_obj, lex_Frame_23_lex15_obj
00359      decont             loc_38_obj, loc_38_obj
00360      prepargs           Callsite_0
00361      arg_o              0, loc_1_obj
00362      invoke_v           loc_38_obj
00363      getlex             loc_38_obj, lex_Frame_23_lex1_obj
00364      const_s            loc_22_str, 'END;'
00365      decont             loc_57_obj, loc_38_obj
00366      findmeth           loc_56_obj, loc_57_obj, 'say'
00367      prepargs           Callsite_1
00368      arg_o              0, loc_38_obj
00369      arg_s              1, loc_22_str
00370      invoke_o           loc_56_obj, loc_56_obj
00371      goto               label_25(00418)
     annotation: gen/moar/stage2/NQPHLL.nqp:738
     label_20:
00372      const_s            loc_22_str, '{{{PROFILER_OUTPUT}}}'
00373      split              loc_38_obj, loc_22_str, loc_17_str
00374      set                loc_58_obj, loc_38_obj
00375      getlex             loc_38_obj, lex_Frame_23_lex1_obj
00376      const_i64_16       loc_42_int, 0
00377      atpos_o            loc_57_obj, loc_58_obj, loc_42_int
00378      ifnonnull          loc_57_obj, label_21(00382)
00379      wval               loc_60_obj, 1, 44
00380      set                loc_59_obj, loc_60_obj
00381      goto               label_22(00383)
     label_21:
00382      set                loc_59_obj, loc_57_obj
     label_22:
00383      decont             loc_57_obj, loc_38_obj
00384      findmeth           loc_60_obj, loc_57_obj, 'print'
00385      prepargs           Callsite_2
00386      arg_o              0, loc_38_obj
00387      arg_o              1, loc_59_obj
00388      invoke_o           loc_60_obj, loc_60_obj
00389      getlex             loc_59_obj, lex_Frame_23_lex13_obj
00390      decont             loc_59_obj, loc_59_obj
00391      prepargs           Callsite_0
00392      arg_o              0, loc_1_obj
00393      invoke_v           loc_59_obj
00394      getlex             loc_59_obj, lex_Frame_23_lex1_obj
00395      const_s            loc_22_str, ''
00396      getlex             loc_38_obj, lex_Frame_23_lex0_obj
00397      join               loc_22_str, loc_22_str, loc_38_obj
00398      decont             loc_57_obj, loc_59_obj
00399      findmeth           loc_38_obj, loc_57_obj, 'print'
00400      prepargs           Callsite_1
00401      arg_o              0, loc_59_obj
00402      arg_s              1, loc_22_str
00403      invoke_o           loc_38_obj, loc_38_obj
00404      getlex             loc_59_obj, lex_Frame_23_lex1_obj
00405      const_i64_16       loc_42_int, 1
00406      atpos_o            loc_57_obj, loc_58_obj, loc_42_int
00407      ifnonnull          loc_57_obj, label_23(00411)
00408      wval               loc_62_obj, 1, 44
00409      set                loc_61_obj, loc_62_obj
00410      goto               label_24(00412)
     label_23:
00411      set                loc_61_obj, loc_57_obj
     label_24:
00412      decont             loc_57_obj, loc_59_obj
00413      findmeth           loc_62_obj, loc_57_obj, 'print'
00414      prepargs           Callsite_2
00415      arg_o              0, loc_59_obj
00416      arg_o              1, loc_61_obj
00417      invoke_o           loc_62_obj, loc_62_obj
     label_25:
00418      getlex             loc_61_obj, lex_Frame_23_lex1_obj
00419      decont             loc_57_obj, loc_61_obj
00420      findmeth           loc_59_obj, loc_57_obj, 'close'
00421      prepargs           Callsite_0
00422      arg_o              0, loc_61_obj
00423      invoke_o           loc_59_obj, loc_59_obj
00424      return_o           loc_59_obj
(gdb)
```

**Comment by MasterDuke17** [comment]
I'm closing this. It used to segv after one or two attempts, but it's now been running for an hour or two without a single problem. No idea what fixed it.
