### ISSUE TITLE
Segfault when taking a heap snapshot

### ISSUE THREAD

**Issue by Altai-man** [MoarVM/MoarVM#1602]
Steps to reproduce:

- Clone `cro-http` repo at latest, also need latest version of cro-core installed
- `rakudo-m --profile=heap-snapshot --profile-kind=heap -Ilib t/http-server.t`

Output of `where` and `info threads` in gdb:

```
(gdb) r
Starting program: /home/koto/Devel/perl6-dev/R/rakudo/install/bin/rakudo-m --profile=heap-snapshot --profile-kind=heap -I/home/koto/Work/cro/cro-http/lib -I/home/koto/Work/cro/cro-core/lib /home/koto/Work/cro/cro-http/t/http-server.t
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff6f10640 (LWP 142148)]
ok 1 - Service does Cro::Service
[New Thread 0x7fffedece640 (LWP 142149)]
[New Thread 0x7fffed6cd640 (LWP 142150)]
[New Thread 0x7fffecea2640 (LWP 142151)]
ok 2 - Server not listening until started
[New Thread 0x7fffdffff640 (LWP 142152)]
ok 3 - Can start service
ok 4 - Can connect once service is started
[New Thread 0x7fffdf7fe640 (LWP 142155)]

Thread 6 "rakudo-m" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdffff640 (LWP 142152)]
0x00007ffff79f7421 in process_collectable (sc_cache=<synthetic pointer>, c=0x7fffd8303418, col=0x7fffdfffdf50, ss=0x7fffdfffdf70, tc=0x9a49850)
    at src/profiler/heapsnapshot.c:414
414	                (MVMCollectable *)tc->instance->all_scs[sc_idx]->sc), sc_cache);
(gdb) where
#0  0x00007ffff79f7421 in process_collectable (sc_cache=<synthetic pointer>, c=0x7fffd8303418, col=0x7fffdfffdf50, ss=0x7fffdfffdf70, tc=0x9a49850)
    at src/profiler/heapsnapshot.c:414
#1  process_object (sc_cache=<synthetic pointer>, stable_cache=<synthetic pointer>, obj=0x7fffd8303418, col=0x7fffdfffdf50, ss=0x7fffdfffdf70, tc=0x9a49850)
    at src/profiler/heapsnapshot.c:466
#2  process_workitems (ss=0x7fffdfffdf70, tc=0x9a49850) at src/profiler/heapsnapshot.c:509
#3  record_snapshot (tc=tc@entry=0x9a49850, col=col@entry=0xcd6b0f0, hs=<optimized out>) at src/profiler/heapsnapshot.c:758
#4  0x00007ffff79f869a in MVM_profile_heap_take_snapshot (tc=tc@entry=0x9a49850) at src/profiler/heapsnapshot.c:1881
#5  0x00007ffff79247d6 in finish_gc (is_coordinator=<optimized out>, gen=0 '\000', tc=0x9a49850) at src/gc/orchestrate.c:187
#6  run_gc (tc=tc@entry=0x9a49850, what_to_do=what_to_do@entry=0 '\000') at src/gc/orchestrate.c:448
#7  0x00007ffff7925389 in MVM_gc_enter_from_allocator (tc=tc@entry=0x9a49850) at src/gc/orchestrate.c:599
#8  0x00007ffff7925651 in MVM_gc_allocate_nursery (tc=0x9a49850, size=184) at src/gc/allocation.c:37
#9  0x00007ffff792596a in MVM_gc_allocate (size=184, tc=tc@entry=0x9a49850) at src/gc/allocation.h:15
#10 MVM_gc_allocate_zeroed (size=184, tc=tc@entry=0x9a49850) at src/gc/allocation.h:21
#11 MVM_gc_allocate_frame (tc=tc@entry=0x9a49850) at src/gc/allocation.c:99
#12 0x00007ffff78fe15a in MVM_frame_move_to_heap (tc=tc@entry=0x9a49850, frame=0x7fffd81acf38) at src/core/frame.c:664
#13 0x00007ffff78fe6a8 in MVM_frame_force_to_heap (frame=<optimized out>, tc=0x9a49850) at src/core/frame.h:153
#14 allocate_frame (tc=tc@entry=0x9a49850, static_frame=<optimized out>, spesh_cand=<optimized out>, heap=heap@entry=1) at src/core/frame.c:283
#15 0x00007ffff78fe8f2 in MVM_frame_dispatch (tc=tc@entry=0x9a49850, code=<optimized out>, args=..., spesh_cand=0, spesh_cand@entry=-1) at src/core/frame.c:550
#16 0x00007ffff797af93 in run_dispatch (tc=0x9a49850, record=record@entry=0x7fffd81acff0, disp=0x27d87a0, capture=<optimized out>, thunked=thunked@entry=0x0)
    at src/disp/program.c:533
#17 0x00007ffff7984de7 in MVM_disp_program_record_end (tc=tc@entry=0x9a49850, record=record@entry=0x7fffd81acff0, thunked=0x0) at src/disp/program.c:2762
#18 0x00007ffff7903f8b in handle_end_of_dispatch_record (thunked=<optimized out>, tc=0x9a49850) at src/core/callstack.c:436
#19 MVM_callstack_unwind_dispatch_record (tc=tc@entry=0x9a49850, thunked=thunked@entry=0x0) at src/core/callstack.c:591
#20 0x00007ffff797b001 in run_dispatch (tc=tc@entry=0x9a49850, record=record@entry=0x7fffd81acff0, disp=disp@entry=0x41f1f0, capture=capture@entry=0x7fffd8321bd0, 
    thunked=thunked@entry=0x0) at src/disp/program.c:526
#21 0x00007ffff797ea26 in MVM_disp_program_run_dispatch (tc=0x9a49850, disp=0x41f1f0, arg_info=..., ic_entry_ptr=<optimized out>, ic_entry=<optimized out>, 
    update_sf=<optimized out>) at src/disp/program.c:598
#22 0x00007ffff78efce0 in MVM_interp_run (tc=tc@entry=0x9a49850, initial_invoke=0x7fffdfffdf70, initial_invoke@entry=0x7ffff7908910 <thread_initial_invoke>, 
    invoke_data=0x7fffdfffdf70, invoke_data@entry=0x7ffff7908910 <thread_initial_invoke>, outer_runloop=outer_runloop@entry=0x0) at src/core/interp.c:5433
#23 0x00007ffff7908a39 in start_thread (data=0x9a4b810) at src/core/threads.c:101
#24 0x00007ffff7395299 in start_thread (arg=0x7fffdffff640) at pthread_create.c:481
#25 0x00007ffff75f1353 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) info threads
  Id   Target Id                                            Frame 
  1    Thread 0x7ffff7375740 (LWP 142137) "rakudo-m"        0x00007ffff73a1a8a in __futex_abstimed_wait_common64 (futex_word=futex_word@entry=0x447ab10, expected=expected@entry=0, 
    clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>, cancel=cancel@entry=true) at ../sysdeps/nptl/futex-internal.c:74
  2    Thread 0x7ffff6f10640 (LWP 142148) "spesh optimizer" 0x00007ffff73a1a8a in __futex_abstimed_wait_common64 (futex_word=futex_word@entry=0x405734, expected=expected@entry=0, 
    clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ../sysdeps/nptl/futex-internal.c:74
  3    Thread 0x7fffedece640 (LWP 142149) "rakudo-m"        0x00007ffff73a1a8a in __futex_abstimed_wait_common64 (futex_word=futex_word@entry=0x405734, expected=expected@entry=0, 
    clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ../sysdeps/nptl/futex-internal.c:74
  4    Thread 0x7fffed6cd640 (LWP 142150) "rakudo-m"        0x00007ffff73a1a8a in __futex_abstimed_wait_common64 (futex_word=futex_word@entry=0x405760, expected=expected@entry=0, 
    clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ../sysdeps/nptl/futex-internal.c:74
  5    Thread 0x7fffecea2640 (LWP 142151) "async io thread" 0x00007ffff73a1a8a in __futex_abstimed_wait_common64 (futex_word=futex_word@entry=0x405734, expected=expected@entry=0, 
    clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ../sysdeps/nptl/futex-internal.c:74
* 6    Thread 0x7fffdffff640 (LWP 142152) "rakudo-m"        0x00007ffff79f7421 in process_collectable (sc_cache=<synthetic pointer>, c=0x7fffd8303418, col=0x7fffdfffdf50, 
    ss=0x7fffdfffdf70, tc=0x9a49850) at src/profiler/heapsnapshot.c:414
  7    Thread 0x7fffdf7fe640 (LWP 142155) "rakudo-m"        0x00007ffff73a1a8a in __futex_abstimed_wait_common64 (futex_word=futex_word@entry=0x4bc0d0, expected=expected@entry=0, 
    clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ../sysdeps/nptl/futex-internal.c:74
(gdb) 

```

**Comment by Altai-man** [comment]
Cannot reproduce on latest.
