### ISSUE TITLE
Bytecode validation error

### ISSUE THREAD

**Issue by alabamenhu** [MoarVM/MoarVM#1626]
Here is the golfed code that triggers this:

```raku
class A { 
    has int32 $.b is rw 
}

sub foo(int32 $c is rw) {
    $c += 1
}

my $a = A.new: :0b; 

foo $a;
```

The `is rw` and specified lengths seems to be key (`is raw` also triggers, and `s/int32/int` results in no problems).

Per @MasterDuke17  on IRC, this may be solved by @niner 's work on unsigned ints, and per @dogbert17 , this is likely due to some optimization bugs.

**Comment by MasterDuke17** [comment]
Some info:
```
[dan@alexandria perl6]$ MVM_SPESH_DISABLE=1 gdb --args raku -e 'class A { has int32 $.b is rw }; sub foo(int32 $c is rw) { $c += 1 }; my $a = A.new: :0b; foo $a.b;'
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./install/bin/raku...
(gdb) b fail
Function "fail" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (fail) pending.
(gdb) r
Starting program: /home/dan/Source/perl6/install/bin/raku -e class\ A\ \{\ has\ int32\ \$.b\ is\ rw\ \}\;\ sub\ foo\(int32\ \$c\ is\ rw\)\ \{\ \$c\ +=\ 1\ \}\;\ my\ \$a\ =\ A.new:\ :0b\;\ foo\ \$a.b\;
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Breakpoint 1, fail (val=val@entry=0x7fffffffd7a0, msg=msg@entry=0x7ffff79f0700 "Bytecode validation error at offset %u, instruction %u:\noperand type %u does not match register type %u for op %s in frame %s") at src/core/validation.c:60
60      static void fail(Validator *val, const char *msg, ...) {
(gdb) bt
#0  fail (val=val@entry=0x7fffffffd7a0, msg=msg@entry=0x7ffff79f0700 "Bytecode validation error at offset %u, instruction %u:\noperand type %u does not match register type %u for op %s in frame %s") at src/core/validation.c:60
#1  0x00007ffff788f4f6 in validate_reg_operand (val=0x7fffffffd7a0, flags=<optimized out>) at src/core/validation.c:295
#2  0x00007ffff788f8bf in validate_operand (val=val@entry=0x7fffffffd7a0, flags=<optimized out>) at src/core/validation.c:364
#3  0x00007ffff788fa47 in validate_operands (val=val@entry=0x7fffffffd7a0) at src/core/validation.c:464
#4  0x00007ffff78901a5 in MVM_validate_static_frame (tc=tc@entry=0x55555555a120, static_frame=0x555557637230) at src/core/validation.c:589
#5  0x00007ffff78897ce in prepare_and_verify_static_frame (static_frame=0x555557637230, tc=0x55555555a120) at src/core/frame.c:49
#6  instrumentation_level_barrier (static_frame=<optimized out>, tc=0x55555555a120) at src/core/frame.c:88
#7  MVM_frame_dispatch (tc=tc@entry=0x55555555a120, code=<optimized out>, args=..., spesh_cand=spesh_cand@entry=-1) at src/core/frame.c:464
#8  0x00007ffff79196ec in MVM_disp_program_record_end (tc=tc@entry=0x55555555a120, record=record@entry=0x7ffff7641ff8) at src/disp/program.c:3156
#9  0x00007ffff788f018 in handle_end_of_dispatch_record (tc=0x55555555a120) at src/core/callstack.c:568
#10 MVM_callstack_unwind_dispatch_record (tc=0x55555555a120) at src/core/callstack.c:870
#11 0x00007ffff790d9ad in run_dispatch (tc=<optimized out>, record=record@entry=0x7ffff7641ff8, disp=<optimized out>, capture=<optimized out>) at src/disp/program.c:533
#12 0x00007ffff791956c in MVM_disp_program_record_end (tc=tc@entry=0x55555555a120, record=record@entry=0x7ffff7641ff8) at src/disp/program.c:3078
#13 0x00007ffff788eae2 in handle_end_of_dispatch_record (tc=0x55555555a120) at src/core/callstack.c:568
#14 cleanup_dispatch_record_record (exceptional=0 '\000', tc=0x55555555a120) at src/core/callstack.c:666
#15 MVM_callstack_unwind_frame (tc=tc@entry=0x55555555a120, exceptional=exceptional@entry=0 '\000') at src/core/callstack.c:838
#16 0x00007ffff7889f2a in MVM_frame_try_return (tc=0x55555555a120) at src/core/frame.c:937
#17 0x00007ffff7877d2f in MVM_interp_run (tc=0x7fffffffd7a0, initial_invoke=0x7ffff79f0700, initial_invoke@entry=0x7ffff7998d90 <toplevel_initial_invoke>, invoke_data=0x7ffff79f0700, 
    invoke_data@entry=0x7ffff7998d90 <toplevel_initial_invoke>, outer_runloop=0x9, outer_runloop@entry=0x0) at src/core/interp.c:567
#18 0x00007ffff7999ea5 in MVM_vm_run_file (instance=instance@entry=0x555555559590, filename=filename@entry=0x555555559520 "/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm") at src/moar.c:505
#19 0x00005555555557d8 in main (argc=<optimized out>, argv=0x7fffffffe338) at src/vm/moar/runner/main.c:474
(gdb) f 4
#4  0x00007ffff78901a5 in MVM_validate_static_frame (tc=tc@entry=0x55555555a120, static_frame=0x555557637230) at src/core/validation.c:589
589                     validate_operands(val);
(gdb) call MVM_dump_bytecode(tc)
00000      getcode            loc_5_obj, Frame_2
00001      capturelex         loc_5_obj
00002      getcode            loc_5_obj, Frame_3
00003      capturelex         loc_5_obj
00004      getcode            loc_5_obj, Frame_4
00005      capturelex         loc_5_obj
00006      getcode            loc_11_obj, Frame_5
00007      takeclosure        loc_11_obj, loc_11_obj
00008      checkarity         0, 0
00009      paramnamesused     
     annotation: -e:1
00010      getcode            loc_1_obj, Frame_2
00011      getcode            loc_2_obj, Frame_3
00012      getcode            loc_3_obj, Frame_4
00013      wval               loc_4_obj, 2, 28
00014      create             loc_4_obj, loc_4_obj
00015      wval               loc_5_obj, 2, 28
00016      wval               loc_6_obj, 0, 34
00017      bindattr_o         loc_4_obj, loc_5_obj, '$!descriptor', loc_6_obj, -1
00018      wval               loc_6_obj, 2, 28
00019      wval               loc_5_obj, 2, 24
00020      bindattr_o         loc_4_obj, loc_6_obj, '$!value', loc_5_obj, -1
00021      set                loc_0_obj, loc_4_obj
00022      const_s            loc_8_str, '$*CTXSAVE'
00023      getdynlex          loc_4_obj, loc_8_str
00024      set                loc_7_obj, loc_4_obj
00025      isnull             loc_9_int, loc_7_obj
00026      if_i               loc_9_int, label_1(00037)
00027      decont             loc_4_obj, loc_7_obj
00028      const_s            loc_8_str, 'ctxsave'
00029      const_i64_16       loc_10_int, 0
00030      dispatch_o         loc_5_obj, 'lang-find-meth', Callsite_1, loc_4_obj, loc_8_str, loc_10_int
00031      isnull             loc_10_int, loc_5_obj
00032      not_i              loc_10_int, loc_10_int
00033      unless_i           loc_10_int, label_1(00037)
00034      decont             loc_5_obj, loc_7_obj
00035      const_s            loc_8_str, 'ctxsave'
00036      dispatch_v         'lang-meth-call', Callsite_2, loc_5_obj, loc_8_str, loc_7_obj
     annotation: -e:1
     label_1:
00037      dispatch_v         'boot-code', Callsite_0, loc_11_obj
     annotation: -e:1
00038      set                loc_5_obj, loc_0_obj
00039      wval               loc_4_obj, 0, 12
00040      decont             loc_6_obj, loc_4_obj
00041      const_s            loc_8_str, 'new'
00042      wval               loc_12_obj, 0, 29
00043      dispatch_o         loc_12_obj, 'lang-meth-call', Callsite_3, loc_6_obj, loc_8_str, loc_4_obj, loc_12_obj
00044      dispatch_o         loc_4_obj, 'lang-hllize', Callsite_0, loc_12_obj
00045      decont             loc_4_obj, loc_4_obj
00046      dispatch_v         'raku-assign', Callsite_4, loc_5_obj, loc_4_obj
     annotation: -e:1
00047      const_s            loc_8_str, '&foo'
00048      getlexstatic_o     loc_5_obj, loc_8_str
00049      decont             loc_5_obj, loc_5_obj
00050      decont             loc_4_obj, loc_0_obj
00051      const_s            loc_8_str, 'b'
00052      dispatch_o         loc_4_obj, 'lang-meth-call', Callsite_2, loc_4_obj, loc_8_str, loc_0_obj
00053      dispatch_o         loc_12_obj, 'lang-hllize', Callsite_0, loc_4_obj
00054      dispatch_o         loc_12_obj, 'lang-call', Callsite_5, loc_5_obj, loc_12_obj
00055   -> dispatch_v         'raku-sink', Callsite_0, loc_12_obj
00056      wval               loc_12_obj, 2, 25
00057      return_o           loc_12_obj
(gdb)
```

**Comment by dogbert17** [comment]
dogbert@dogbert-VirtualBox:~$ perl6 -v
    Welcome to Rakudo™ v2022.02-76-g451ad0ea6.
    Implementing the Raku® Programming Language v6.d.
    Built on MoarVM version 2022.02-3-g420b68f06.
    dogbert@dogbert-VirtualBox:~$ cat test.pl6
    class A { 
        has int32 $.b is rw 
    }
    
    sub foo(int32 $c is rw) {
        $c += 1
    }
    
    my $a = A.new: :0b; 
    
    foo $a;
    dogbert@dogbert-VirtualBox:~$ perl6 --optimize=0 test.pl6
    Expected a modifiable native int argument for '$c'
      in sub foo at test.pl6 line 5
      in block <unit> at test.pl6 line 11
