### ISSUE TITLE
t/spec/S17-supply/syntax.t fails when running MoarVM with a small nursery

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#449]
# The following changes had been made to the MoarVM src in preparation
--- a/src/core/fixedsizealloc.c
+++ b/src/core/fixedsizealloc.c
 /* Turn this on to switch to a mode where we debug by size. */
-#define FSA_SIZE_DEBUG 0
+#define FSA_SIZE_DEBUG 1

--- a/src/gc/collect.h
+++ b/src/gc/collect.h
-#define MVM_NURSERY_SIZE 4194304
+#define MVM_NURSERY_SIZE (32768 * 2)
 
--- a/src/gc/debug.h
+++ b/src/gc/debug.h
-#define MVM_GC_DEBUG 0
+#define MVM_GC_DEBUG 1
 
# running the code under gdb produces seemingly different errors

# run 1
dogbert@dogbert-VirtualBox ~/repos/rakudo $ gdb --args /home/dogbert/repos/rakudo/install/bin/moar --libpath="/home/dogbert/repos/rakudo/install/share/nqp/lib" --libpath="." /home/dogbert/repos/rakudo/perl6.moarvm t/spec/S17-supply/syntax.t
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/dogbert/repos/rakudo/install/bin/moar...done.
(gdb) break MVM_panic
Function "MVM_panic" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (MVM_panic) pending.
(gdb) r
Starting program: /home/dogbert/repos/rakudo/install/bin/moar --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=. /home/dogbert/repos/rakudo/perl6.moarvm t/spec/S17-supply/syntax.t
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
1..68
ok 1 - Got two values emitted by supply
ok 2 - First value correct
ok 3 - Second value correct
ok 4 - Tapping the supply another time works
ok 5 - Only the one emit ran, due to done
ok 6 - Got correct value emitted
ok 7 - Did not continue running code after done
ok 8 - Block with emit then done runs emit subscription once
ok 9 - Block with emit then done runs done subscription once
ok 10 - Block with emit then done never runs quit subscription
ok 11 - Block with emit runs emit subscription once
ok 12 - Block with emit runs done subscription once (automatically)
ok 13 - Block with emit never runs quit subscription
ok 14 - Block with emit then die runs emit subscription once
ok 15 - Block with emit then die never runs done subscription once
ok 16 - Block with emit then die runs quit subscription once
ok 17 - whenever loop ran and emitted first event into supply...
ok 18 - ...and emitted correct first value
ok 19 - whenever loop ran and emitted second event into supply...
ok 20 - ...and emitted correct second value
ok 21 - done not run automatically when there is a whenever
ok 22 - no unexpected quit when there is a whenever
ok 23 - done is run if the whenever gets done
ok 24 - still no unexpected quit
ok 25 - whenever loop produced three values
ok 26 - First value from loop iteration correct
ok 27 - Second value from loop iteration correct
ok 28 - Value from LAST block correct
ok 29 - Multiple whenevers run concurrently
ok 30 - supply block with two whenevers then done runs its done
ok 31 - first whenever closes its supply due to the done
ok 32 - second whenever closes its supply due to the done
ok 33 - take-until style supply emitted correct values
ok 34 - take-until style supply is done after second supply emits
ok 35 - first supply tapped was closed
ok 36 - second supply tapped was closed
ok 37 - supply block with two whenevers starts out not done
ok 38 - still not done after one whenever gets done
ok 39 - but done after all whenevers get done
ok 40 - supply block with whenever that gets a quit emits no values
ok 41 - supply block with whenever that gets a quit is not done
ok 42 - supply block with whenever that gets a quit does quit
ok 43 - emits up to, and emit in a QUIT block, all came out OK
ok 44 - done inside of matched QUIT block worked
ok 45 - did not produce a quit, since exception handled
ok 46 - supply with one whenever that quits but handles it will be done
ok 47 - ...and the handled exception will not cause a quit
ok 48 - supply with one whenever that quits, and QUIT does not match, will still quit
ok 49 - ...and done will not be run
ok 50 - react/whenever with supply that immediately emits values works
[New Thread 0xb6611b40 (LWP 4462)]
[New Thread 0xb5cffb40 (LWP 4463)]
ok 51 - Can only be in one whatever block at a time
    1..3
    ok 1 - 'emit 42' died
    ok 2 - right exception type (X::ControlFlow)
    ok 3 - .illegal matches emit
ok 52 - did we throws-like X::ControlFlow?
    1..3
    ok 1 - 'done' died
    ok 2 - right exception type (X::ControlFlow)
    ok 3 - .illegal matches done
ok 53 - did we throws-like X::ControlFlow?
[New Thread 0xb52ffb40 (LWP 4464)]
ok 54 - can use channels with whenever
[New Thread 0xb48ffb40 (LWP 4465)]
[New Thread 0xb40feb40 (LWP 4466)]
[New Thread 0xb38fdb40 (LWP 4467)]
[New Thread 0xb30fcb40 (LWP 4468)]
[New Thread 0xb28fbb40 (LWP 4469)]
[New Thread 0xb20fab40 (LWP 4470)]
ok 55 - multiple channels in whenever blocks work
ok 56 - supply block with CLOSE phaser works as normal
ok 57 - CLOSE phaser not run yet
ok 58 - CLOSE phaser run on tap close
ok 59 - CLOSE phaser runs also on normal termination
ok 60 - CLOSE phasers do not run twice (normal termination then .close)
ok 61 - LAST in whenever triggered without iterations sees correct outer (1)
ok 62 - LAST in whenever triggered without iterations sees correct outer (2)
ok 63 - QUIT properly handles exception even when dieing synchronously with the .tap
ok 64 - QUIT in whenever triggered without iterations sees correct outer (1)
ok 65 - QUIT in whenever triggered without iterations sees correct outer (2)
[New Thread 0xb18f9b40 (LWP 4471)]
[New Thread 0xb10f8b40 (LWP 4472)]
[New Thread 0xb08f7b40 (LWP 4473)]
[New Thread 0xb00f6b40 (LWP 4474)]
[New Thread 0xaf6ffb40 (LWP 4475)]
[New Thread 0xaeefeb40 (LWP 4476)]
ok 66 - Never get done message twice from a supply
[New Thread 0xae6fdb40 (LWP 4477)]
[New Thread 0xadefcb40 (LWP 4478)]
ok 67 - No react guts crash in case that once spat out two done messages either
moar: src/6model/sc.h:163: MVM_SC_WB_OBJ: Assertion `!(obj->header.flags & MVM_CF_GEN2_LIVE)' failed.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0xb10f8b40 (LWP 4472)]
0xb7fdccb0 in ?? ()
(gdb) bt
#0  0xb7fdccb0 in ?? ()
#1  0xb7ccbfa3 in MVM_interp_run (tc=0xb3a1200, initial_invoke=0xb7cf3e49 <thread_initial_invoke>, invoke_data=0xab13410) at src/core/interp.c:2194
#2  0xb7cf3f8b in start_thread (data=0xab13410) at src/core/threads.c:77
#3  0xb7de5937 in uv.thread_start () from //home/dogbert/repos/rakudo/install/lib/libmoar.so
#4  0xb7a0ef72 in start_thread (arg=0xb10f8b40) at pthread_create.c:312
#5  0xb7b56f8e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129

# run 2
dogbert@dogbert-VirtualBox ~/repos/rakudo $ gdb --args /home/dogbert/repos/rakudo/install/bin/moar --libpath="/home/dogbert/repos/rakudo/install/share/nqp/lib" --libpath="." /home/dogbert/repos/rakudo/perl6.moarvm t/spec/S17-supply/syntax.t
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/dogbert/repos/rakudo/install/bin/moar...done.
(gdb) break MVM_panic
Function "MVM_panic" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (MVM_panic) pending.
(gdb) r
Starting program: /home/dogbert/repos/rakudo/install/bin/moar --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=. /home/dogbert/repos/rakudo/perl6.moarvm t/spec/S17-supply/syntax.t
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
1..68
ok 1 - Got two values emitted by supply
ok 2 - First value correct
ok 3 - Second value correct
ok 4 - Tapping the supply another time works
ok 5 - Only the one emit ran, due to done
ok 6 - Got correct value emitted
ok 7 - Did not continue running code after done
ok 8 - Block with emit then done runs emit subscription once
ok 9 - Block with emit then done runs done subscription once
ok 10 - Block with emit then done never runs quit subscription
ok 11 - Block with emit runs emit subscription once
ok 12 - Block with emit runs done subscription once (automatically)
ok 13 - Block with emit never runs quit subscription
ok 14 - Block with emit then die runs emit subscription once
ok 15 - Block with emit then die never runs done subscription once
ok 16 - Block with emit then die runs quit subscription once
ok 17 - whenever loop ran and emitted first event into supply...
ok 18 - ...and emitted correct first value
ok 19 - whenever loop ran and emitted second event into supply...
ok 20 - ...and emitted correct second value
ok 21 - done not run automatically when there is a whenever
ok 22 - no unexpected quit when there is a whenever
ok 23 - done is run if the whenever gets done
ok 24 - still no unexpected quit
ok 25 - whenever loop produced three values
ok 26 - First value from loop iteration correct
ok 27 - Second value from loop iteration correct
ok 28 - Value from LAST block correct
ok 29 - Multiple whenevers run concurrently
ok 30 - supply block with two whenevers then done runs its done
ok 31 - first whenever closes its supply due to the done
ok 32 - second whenever closes its supply due to the done
ok 33 - take-until style supply emitted correct values
ok 34 - take-until style supply is done after second supply emits
ok 35 - first supply tapped was closed
ok 36 - second supply tapped was closed
ok 37 - supply block with two whenevers starts out not done
ok 38 - still not done after one whenever gets done
ok 39 - but done after all whenevers get done
ok 40 - supply block with whenever that gets a quit emits no values
ok 41 - supply block with whenever that gets a quit is not done
ok 42 - supply block with whenever that gets a quit does quit
ok 43 - emits up to, and emit in a QUIT block, all came out OK
ok 44 - done inside of matched QUIT block worked
ok 45 - did not produce a quit, since exception handled
ok 46 - supply with one whenever that quits but handles it will be done
ok 47 - ...and the handled exception will not cause a quit
ok 48 - supply with one whenever that quits, and QUIT does not match, will still quit
ok 49 - ...and done will not be run
ok 50 - react/whenever with supply that immediately emits values works
[New Thread 0xb6611b40 (LWP 4502)]
[New Thread 0xb5cffb40 (LWP 4503)]
ok 51 - Can only be in one whatever block at a time
    1..3
    ok 1 - 'emit 42' died
    ok 2 - right exception type (X::ControlFlow)
    ok 3 - .illegal matches emit
ok 52 - did we throws-like X::ControlFlow?
    1..3
    ok 1 - 'done' died
    ok 2 - right exception type (X::ControlFlow)
    ok 3 - .illegal matches done
ok 53 - did we throws-like X::ControlFlow?
[New Thread 0xb52ffb40 (LWP 4504)]
ok 54 - can use channels with whenever
[New Thread 0xb48ffb40 (LWP 4505)]
[New Thread 0xb40feb40 (LWP 4506)]
[New Thread 0xb38fdb40 (LWP 4507)]
[New Thread 0xb28fbb40 (LWP 4509)]
[New Thread 0xb30fcb40 (LWP 4508)]
[New Thread 0xb20fab40 (LWP 4510)]
ok 55 - multiple channels in whenever blocks work
ok 56 - supply block with CLOSE phaser works as normal
ok 57 - CLOSE phaser not run yet
ok 58 - CLOSE phaser run on tap close
ok 59 - CLOSE phaser runs also on normal termination
ok 60 - CLOSE phasers do not run twice (normal termination then .close)
ok 61 - LAST in whenever triggered without iterations sees correct outer (1)
ok 62 - LAST in whenever triggered without iterations sees correct outer (2)
ok 63 - QUIT properly handles exception even when dieing synchronously with the .tap
ok 64 - QUIT in whenever triggered without iterations sees correct outer (1)
ok 65 - QUIT in whenever triggered without iterations sees correct outer (2)
[New Thread 0xb18f9b40 (LWP 4511)]
[New Thread 0xb10f8b40 (LWP 4512)]
[New Thread 0xb08f7b40 (LWP 4513)]
[New Thread 0xb00f6b40 (LWP 4514)]
[New Thread 0xaf8f5b40 (LWP 4515)]
[New Thread 0xaf0f4b40 (LWP 4516)]
ok 66 - Never get done message twice from a supply
[New Thread 0xae8f3b40 (LWP 4517)]
[New Thread 0xae0f2b40 (LWP 4518)]
ok 67 - No react guts crash in case that once spat out two done messages either
[Switching to Thread 0xb00f6b40 (LWP 4514)]

Breakpoint 1, MVM_panic (exitCode=1, messageFormat=0xb7deb5b8 "Collectable %p in fromspace accessed") at src/core/exceptions.c:781
781	    fprintf(stderr, "MoarVM panic: ");
(gdb) bt
#0  MVM_panic (exitCode=1, messageFormat=0xb7deb5b8 "Collectable %p in fromspace accessed") at src/core/exceptions.c:781
#1  0xb7cbe72d in MVM_interp_run (tc=0xb513360, initial_invoke=0xb7cf3e49 <thread_initial_invoke>, invoke_data=0xa26e848) at src/core/interp.c:325
#2  0xb7cf3f8b in start_thread (data=0xa26e848) at src/core/threads.c:77
#3  0xb7de5937 in uv.thread_start () from //home/dogbert/repos/rakudo/install/lib/libmoar.so
#4  0xb7a0ef72 in start_thread (arg=0xb00f6b40) at pthread_create.c:312
#5  0xb7b56f8e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129
(gdb) frame 1
#1  0xb7cbe72d in MVM_interp_run (tc=0xb513360, initial_invoke=0xb7cf3e49 <thread_initial_invoke>, invoke_data=0xa26e848) at src/core/interp.c:325
325	                    MVM_ASSIGN_REF(tc, &(f->header), GET_LEX(cur_op, 0, f).o,
(gdb) p MVM_dump_backtrace(tc)
   at <unknown>:1  (./CORE.setting.moarvm:)
 from SETTING::src/core/ThreadPoolScheduler.pm:41  (./CORE.setting.moarvm:)
 from SETTING::src/core/Thread.pm:30  (./CORE.setting.moarvm:THREAD-ENTRY)
$1 = void

**Comment by dogbert17** [comment]
Fixed by jnthn++ with commit c45cb0ecfd6f28e05d272a27dd0ac24eaea5dbdd
