### ISSUE TITLE
t/spec/S15-nfg/many-threads.t fails with 128k nursery

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#452]
In fact, several async related tests fail under the these, rather harsh, settings, e.g.
t/spec/S07-hyperrace/hyper.t
t/spec/S07-hyperrace/race.t

# code changes

dogbert@dogbert-VirtualBox ~/repos/rakudo/nqp/MoarVM $ git diff
diff --git a/src/core/fixedsizealloc.c b/src/core/fixedsizealloc.c
index a1aef641..2fe6c5e0 100644
--- a/src/core/fixedsizealloc.c
+++ b/src/core/fixedsizealloc.c
 
 /* Turn this on to switch to a mode where we debug by size. */
-#define FSA_SIZE_DEBUG 0
+#define FSA_SIZE_DEBUG 1

diff --git a/src/gc/collect.h b/src/gc/collect.h
index 11d1e3b5..0f04fa25 100644
--- a/src/gc/collect.h
+++ b/src/gc/collect.h

-#define MVM_NURSERY_SIZE 4194304
+#define MVM_NURSERY_SIZE (32768 * 4)
 
diff --git a/src/gc/debug.h b/src/gc/debug.h
index 31cd3459..cfcf8251 100644
--- a/src/gc/debug.h
+++ b/src/gc/debug.h

-#define MVM_GC_DEBUG 0
+#define MVM_GC_DEBUG 2

# gdb run
dogbert@dogbert-VirtualBox ~/repos/rakudo $ gdb --args /home/dogbert/repos/rakudo/install/bin/moar --libpath="/home/dogbert/repos/rakudo/install/share/nqp/lib" --libpath="." /home/dogbert/repos/rakudo/perl6.moarvm t/spec/S15-nfg/many-threads.t
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/dogbert/repos/rakudo/install/bin/moar...done.
(gdb) break MVM_panic
Function "MVM_panic" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (MVM_panic) pending.
(gdb) r
Starting program: /home/dogbert/repos/rakudo/install/bin/moar --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=. /home/dogbert/repos/rakudo/perl6.moarvm t/spec/S15-nfg/many-threads.t
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
1..4
[New Thread 0xb65dfb40 (LWP 8817)]
[New Thread 0xb5bffb40 (LWP 8818)]
[New Thread 0xb51ffb40 (LWP 8819)]
[New Thread 0xb49feb40 (LWP 8820)]
[Switching to Thread 0xb49feb40 (LWP 8820)]

Breakpoint 1, MVM_panic (exitCode=1, messageFormat=0xb726850c "Collectable %p in fromspace accessed") at src/core/exceptions.c:781
781	    fprintf(stderr, "MoarVM panic: ");
(gdb) bt
#0  MVM_panic (exitCode=1, messageFormat=0xb726850c "Collectable %p in fromspace accessed") at src/core/exceptions.c:781
#1  0xb72671a3 in finish_store () from ./dynext/libperl6_ops_moar.so
#2  0xb7cc922a in MVM_interp_run (tc=0x98b0928, initial_invoke=0xb7cf34ac <thread_initial_invoke>, invoke_data=0x98aef10) at src/core/interp.c:2871
#3  0xb7cf35ee in start_thread (data=0x98aef10) at src/core/threads.c:77
#4  0xb7de4f97 in uv.thread_start () from //home/dogbert/repos/rakudo/install/lib/libmoar.so
#5  0xb7a00f72 in start_thread (arg=0xb49feb40) at pthread_create.c:312
#6  0xb7b48f8e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129
(gdb) frame 2
#2  0xb7cc922a in MVM_interp_run (tc=0x98b0928, initial_invoke=0xb7cf34ac <thread_initial_invoke>, invoke_data=0x98aef10) at src/core/interp.c:2871
2871	                    spec->store_unchecked(tc, cont, obj);
(gdb) p MVM_dump_backtrace(tc)
   at <unknown>:1  (./CORE.setting.moarvm:push-until-lazy)
 from SETTING::src/core/List.pm:243  (./CORE.setting.moarvm:reify-until-lazy)
 from SETTING::src/core/List.pm:691  (./CORE.setting.moarvm:)
 from SETTING::src/core/List.pm:689  (./CORE.setting.moarvm:push-until-lazy)
 from SETTING::src/core/List.pm:256  (./CORE.setting.moarvm:reify-until-lazy)
 from SETTING::src/core/List.pm:536  (./CORE.setting.moarvm:elems)
 from SETTING::src/core/Uni.pm:9  (./CORE.setting.moarvm:new)
 from t/spec/S15-nfg/many-threads.t:7  (<ephemeral file>:)
 from SETTING::src/core/List.pm:1377  (./CORE.setting.moarvm:infix:<xx>)
 from t/spec/S15-nfg/many-threads.t:7  (<ephemeral file>:)
 from SETTING::src/core/Promise.pm:175  (./CORE.setting.moarvm:)
 from SETTING::src/core/ThreadPoolScheduler.pm:163  (./CORE.setting.moarvm:)
 from SETTING::src/core/ThreadPoolScheduler.pm:51  (./CORE.setting.moarvm:)
 from SETTING::src/core/ThreadPoolScheduler.pm:44  (./CORE.setting.moarvm:)
 from SETTING::src/core/ThreadPoolScheduler.pm:41  (./CORE.setting.moarvm:)
 from SETTING::src/core/Thread.pm:30  (./CORE.setting.moarvm:THREAD-ENTRY)
$1 = void

**Comment by dogbert17** [comment]
Fixed by jnthn++ with one or several commits made on Dec. 14th
