### ISSUE TITLE
t/spec/S03-metaops/hyper.t fails with 64k nursery

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#456]
# gdb run

the test failed with 64k nursery but worked with both 32k and 16k

dogbert@dogbert-VirtualBox ~/repos/rakudo $ gdb --args /home/dogbert/repos/rakudo/install/bin/moar --libpath="/home/dogbert/repos/rakudo/install/share/nqp/lib" --libpath="." /home/dogbert/repos/rakudo/perl6.moarvm --nqp-lib=blib -I lib t/spec/S03-metaops/hyper.t
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/dogbert/repos/rakudo/install/bin/moar...done.
(gdb) break MVM_panic
Function "MVM_panic" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (MVM_panic) pending.
(gdb) r
Starting program: /home/dogbert/repos/rakudo/install/bin/moar --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=. /home/dogbert/repos/rakudo/perl6.moarvm --nqp-lib=blib -I lib t/spec/S03-metaops/hyper.t
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".

Breakpoint 1, MVM_panic (exitCode=1, messageFormat=0xb7deaa44 "Collectable %p in fromspace accessed") at src/core/exceptions.c:781
781	    fprintf(stderr, "MoarVM panic: ");
(gdb) bt
#0  MVM_panic (exitCode=1, messageFormat=0xb7deaa44 "Collectable %p in fromspace accessed") at src/core/exceptions.c:781
#1  0xb7caf1d6 in check_reg (tc=0x804c450, reg_base=0xd60bc60, idx=87) at src/core/interp.c:13
#2  0xb7ce0961 in MVM_interp_run (tc=0x804c450, initial_invoke=0xb7dc902a <toplevel_initial_invoke>, invoke_data=0x80a3cc8) at src/core/interp.c:5260
#3  0xb7dc9159 in MVM_vm_run_file (instance=0x804c008, filename=0xbffff2d8 "/home/dogbert/repos/rakudo/perl6.moarvm") at src/moar.c:309
#4  0x08048ea6 in main (argc=8, argv=0xbffff084) at src/main.c:192
(gdb) frame 1
#1  0xb7caf1d6 in check_reg (tc=0x804c450, reg_base=0xd60bc60, idx=87) at src/core/interp.c:13
13	        MVM_ASSERT_NOT_FROMSPACE(tc, reg_base[idx].o);
(gdb) p MVM_dump_backtrace(tc)
   at <unknown>:1  (./blib/Perl6/Actions.moarvm:make_variable_from_parts)
 from gen/moar/Perl6-Actions.nqp:2483  (./blib/Perl6/Actions.moarvm:make_variable)
 from gen/moar/Perl6-Actions.nqp:2411  (./blib/Perl6/Actions.moarvm:variable)
 from gen/moar/stage2/QRegex.nqp:1341  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!reduce)
 from gen/moar/stage2/QRegex.nqp:1302  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!cursor_pass)
 from src/Perl6/Grammar.nqp:2082  (./blib/Perl6/Grammar.moarvm:variable)
 from src/Perl6/Grammar.nqp:2525  (./blib/Perl6/Grammar.moarvm:variable_declarator)
 from src/Perl6/Grammar.nqp:2427  (./blib/Perl6/Grammar.moarvm:declarator)
 from src/Perl6/Grammar.nqp:2498  (./blib/Perl6/Grammar.moarvm:scoped)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:scope_declarator:sym<my>)
 from gen/moar/stage2/QRegex.nqp:1372  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:scope_declarator)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:term:sym<scope_declarator>)
 from gen/moar/stage2/QRegex.nqp:1372  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from src/Perl6/Grammar.nqp:3852  (./blib/Perl6/Grammar.moarvm:termish)
 from gen/moar/stage2/NQPHLL.nqp:927  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:statement)
 from src/Perl6/Grammar.nqp:1180  (./blib/Perl6/Grammar.moarvm:statementlist)
 from src/Perl6/Grammar.nqp:1353  (./blib/Perl6/Grammar.moarvm:blockoid)
 from src/Perl6/Grammar.nqp:1316  (./blib/Perl6/Grammar.moarvm:pblock)
 from src/Perl6/Grammar.nqp:3783  (./blib/Perl6/Grammar.moarvm:circumfix:sym<{ }>)
 from gen/moar/stage2/QRegex.nqp:1378  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:circumfix)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:term:sym<circumfix>)
 from gen/moar/stage2/QRegex.nqp:1378  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:term)
 from src/Perl6/Grammar.nqp:3831  (./blib/Perl6/Grammar.moarvm:termish)
 from gen/moar/stage2/NQPHLL.nqp:927  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:3871  (./blib/Perl6/Grammar.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:1251  (./blib/Perl6/Grammar.moarvm:statement)
 from src/Perl6/Grammar.nqp:1180  (./blib/Perl6/Grammar.moarvm:statementlist)
 from gen/moar/stage2/NQPHLL.nqp:1155  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:LANG)
 from src/Perl6/Grammar.nqp:1595  (./blib/Perl6/Grammar.moarvm:FOREIGN_LANG)
 from src/Perl6/Grammar.nqp:1164  (./blib/Perl6/Grammar.moarvm:comp_unit)
 from src/Perl6/Grammar.nqp:467  (./blib/Perl6/Grammar.moarvm:TOP)
 from gen/moar/stage2/QRegex.nqp:2102  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:1875  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:1825  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:1835  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:1813  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1559  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1780  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:1674  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:27  (./blib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1648  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:47  (/home/dogbert/repos/rakudo/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:38  (/home/dogbert/repos/rakudo/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/dogbert/repos/rakudo/perl6.moarvm:<main>)
 from <unknown>:1  (/home/dogbert/repos/rakudo/perl6.moarvm:<entry>)
$1 = void

# code in interp.c around line 5260
   5259             OP(sp_getarg_s):
   5260                 GET_REG(cur_op, 0).s = tc->cur_frame->params.args[GET_UI16(cur_op, 2)].s;
   5261                 cur_op += 4;
   5262                 goto NEXT;

**Comment by dogbert17** [comment]
Unable to reproduce with 2017.02-217-g030c4c58e built on MoarVM version 2017.02-31-g91aab714
