### ISSUE TITLE
SEGV in t/spec/S17-promise/nonblocking-await.t

### ISSUE THREAD

**Issue by MasterDuke17** [MoarVM/MoarVM#554]
Full output of all the stuff below is at https://gist.github.com/MasterDuke17/c1620e8aebe05c51dfa85e3489223d70.
It was in test 11.
```
    my $c = Channel.new;
    my @proms = (1..100).map: -> $i {
        start {
            await($c) + await($c)
        }
    };
    for 1..100 {
        $c.send($_);
    }
    $c.close;
    #?rakudo.jvm skip 'hangs on JVM'
    throws-like { await @proms }, X::Channel::ReceiveOnClosed,
        'Hundred of outstanding awaits on channels that gets closed works';
```
There seem to be two types of errors. The first is:
```
==31703== Process terminating with default action of signal 6 (SIGABRT): dumping core
==31703==    at 0x55DFA10: raise (in /usr/lib/libc-2.25.so)
==31703==    by 0x55E1139: abort (in /usr/lib/libc-2.25.so)
==31703==    by 0x50913A6: uv_mutex_destroy (thread.c:114)
==31703==    by 0x5011BE1: gc_free (ConcBlockingQueue.c:72)
==31703==    by 0x4FE1518: MVM_gc_collect_free_nursery_uncopied (collect.c:580)
==31703==    by 0x4FDDDC7: MVM_gc_global_destruction (orchestrate.c:530)
==31703==    by 0x50728E1: MVM_vm_destroy_instance (moar.c:397)
==31703== by 0x400D5C: main (main.c:215)
```
The second is:
```
==32198== Thread 17:
==32198== Invalid read of size 8
==32198==    at 0x4FBF215: MVM_interp_run (interp.c:300)
==32198==    by 0x4FCC63D: start_thread (threads.c:80)
==32198==    by 0x50912A6: uv__thread_start (thread.c:49)
==32198==    by 0x5C6A2E6: start_thread (in /usr/lib/libpthread-2.25.so)
==32198==  Address 0x93cec48 is 808 bytes inside a block of size 5,808 free'd
==32198==    at 0x4C2C14B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==32198==    by 0x4FC4DF2: MVM_frame_destroy (frame.c:101)
==32198==    by 0x4FE14DA: MVM_gc_collect_free_nursery_uncopied (collect.c:572)
==32198==    by 0x4FDDDC7: MVM_gc_global_destruction (orchestrate.c:530)
==32198==    by 0x50728E1: MVM_vm_destroy_instance (moar.c:397)
==32198==    by 0x400D5C: main (main.c:215)
==32198==  Block was alloc'd at
==32198==    at 0x4C2AF1F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==32198==    by 0x4FD707A: MVM_malloc (alloc.h:2)
==32198==    by 0x4FD707A: MVM_fixed_size_alloc (fixedsizealloc.c:186)
==32198==    by 0x4FD71BD: MVM_fixed_size_alloc_zeroed (fixedsizealloc.c:194)
==32198==    by 0x4FC440D: allocate_frame (frame.c:231)
==32198==    by 0x4FC535E: MVM_frame_invoke (frame.c:545)
==32198==    by 0x50012E2: invoke_handler (MVMCode.c:10)
==32198==    by 0x4FBB9EE: MVM_interp_run (interp.c:923)
==32198==    by 0x5072788: MVM_vm_run_file (moar.c:310)
==32198==    by 0x400F02: main (main.c:212)
==32198== 
==32198== Invalid read of size 8
==32198==    at 0x501E8EC: MVM_sc_get_object (sc.c:179)
==32198==    by 0x19633573: ???
==32198==    by 0x5047328: MVM_jit_enter_code (compile.c:139)
==32198==    by 0x4FB1096: MVM_interp_run (interp.c:5555)
==32198==    by 0x4FCC63D: start_thread (threads.c:80)
==32198==    by 0x50912A6: uv__thread_start (thread.c:49)
==32198==    by 0x5C6A2E6: start_thread (in /usr/lib/libpthread-2.25.so)
==32198==  Address 0x6363ac0 is 16 bytes inside a block of size 168 free'd
==32198==    at 0x4C2C14B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==32198==    by 0x4FE1518: MVM_gc_collect_free_nursery_uncopied (collect.c:580)
==32198==    by 0x4FDDDC7: MVM_gc_global_destruction (orchestrate.c:530)
==32198==    by 0x50728E1: MVM_vm_destroy_instance (moar.c:397)
==32198==    by 0x400D5C: main (main.c:215)
==32198==  Block was alloc'd at
==32198==    at 0x4C2CF35: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==32198==    by 0x4FC2CFE: MVM_calloc (alloc.h:11)
==32198==    by 0x4FC2CFE: deserialize_sc_deps (bytecode.c:293)
==32198==    by 0x4FC2CFE: MVM_bytecode_unpack (bytecode.c:867)
==32198==    by 0x4FC1731: MVM_cu_from_bytes (compunit.c:21)
==32198==    by 0x4FC1827: MVM_cu_map_from_file (compunit.c:64)
==32198==    by 0x50726F8: MVM_vm_run_file (moar.c:295)
==32198== by 0x400F02: main (main.c:212)
```
Occasionally this error shows up: `MoarVM panic: Corrupt multi dispatch cache: cur_node == 0`. I patched MoarVM to print the actual value of cur_node and then got that error three more times and every time it was == -24.

@dogbert17 caught it in gdb (full output https://gist.github.com/dogbert17/0996beb9635200f468e192b1150a910c):
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb3dfeb40 (LWP 16194)]
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in ?? ()
#1  0xb7c6977a in MVM_repr_elems (tc=tc@entry=0xb421d868, obj=obj@entry=0xb7b6e478 <main_arena+88>) at src/6model/reprconv.c:496
#2  0xb7c6d1db in MVM_6model_parametric_try_find_parameterization (tc=tc@entry=0xb421d868, st=st@entry=0x8e7ae40, params=params@entry=0xb3e087c0) at src/6model/parametric.c:103
#3  0xb7c6d31b in MVM_6model_parametric_parameterize (tc=0xb421d868, type=0x8e7f2d8, params=0xb3e087c0, result=0xb24252f0) at src/6model/parametric.c:74
#4  0xb7c25f9a in MVM_interp_run (tc=tc@entry=0xb421d868, initial_invoke=initial_invoke@entry=0xb7c3ea90 <thread_initial_invoke>, invoke_data=0xb421d868) at src/core/interp.c:4412
#5  0xb7c3ea52 in start_thread (data=0xb42144f8) at src/core/threads.c:80
#6  0xb7d1ebf8 in uv__thread_start (arg=0xb420a4e8) at 3rdparty/libuv/src/unix/thread.c:49
#7  0xb7966f72 in start_thread (arg=0xb3dfeb40) at pthread_create.c:312
#8  0xb7aaef8e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129
(gdb) f 3
#3  0xb7c6d31b in MVM_6model_parametric_parameterize (tc=0xb421d868, type=0x8e7f2d8, params=0xb3e087c0, result=0xb24252f0) at src/6model/parametric.c:74
74	    found = MVM_6model_parametric_try_find_parameterization(tc, st, params);
(gdb) p MVM_dump_backtrace(tc)
   at <unknown>:1  (./blib/Perl6/Metamodel.moarvm:mixin)
 from SETTING::src/core/operators.pm:65  (./CORE.setting.moarvm:infix:<but>)
 from SETTING::src/core.d/await.pm:24  (./CORE.d.setting.moarvm:)
 from SETTING::src/core.d/await.pm:23  (./CORE.d.setting.moarvm:)
 from <unknown>:1  (./CORE.d.setting.moarvm:)
 from SETTING::src/core/Exception.pm:66  (./CORE.setting.moarvm:rethrow)
 from SETTING::src/core/ThreadPoolScheduler.pm:33  (./CORE.setting.moarvm:)
 from SETTING::src/core/ThreadPoolScheduler.pm:18  (./CORE.setting.moarvm:await)
 from SETTING::src/core.d/await.pm:27  (./CORE.d.setting.moarvm:await)
 from t/spec/S17-promise/nonblocking-await.t:121  (<ephemeral file>:)
 from SETTING::src/core/Promise.pm:216  (./CORE.setting.moarvm:)
 from SETTING::src/core/ThreadPoolScheduler.pm:284  (./CORE.setting.moarvm:)
 from SETTING::src/core/ThreadPoolScheduler.pm:167  (./CORE.setting.moarvm:)
 from SETTING::src/core/ThreadPoolScheduler.pm:29  (./CORE.setting.moarvm:)
 from SETTING::src/core/ThreadPoolScheduler.pm:167  (./CORE.setting.moarvm:)
 from SETTING::src/core/ThreadPoolScheduler.pm:165  (./CORE.setting.moarvm:)
 from SETTING::src/core/ThreadPoolScheduler.pm:163  (./CORE.setting.moarvm:)
 from SETTING::src/core/Thread.pm:30  (./CORE.setting.moarvm:THREAD-ENTRY)
$1 = void
```

**Comment by MasterDuke17** [comment]
Valgrind now says:
```
================================================================================================
This is Rakudo Perl 6 running in valgrind, a tool for debugging and profiling programs.
Running a program in valgrind usually takes *a lot* more time than running it directly,
so please be patient.
This Rakudo version is 2017.07.4.g.45.cd.1.a.976 built on MoarVM version 2017.07,
running on arch (4.11.3.1.arch) / linux (4.11.9.1.ARCH)
------------------------------------------------------------------------------------------------
==13643== Memcheck, a memory error detector
==13643== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==13643== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==13643== Command: /home/dan/Source/perl6/install/bin/moar --full-cleanup --execname=./perl6-valgrind-m --libpath=/home/dan/Source/perl6/install/share/nqp/lib --libpath=/home/dan/Source/perl6/install/share/nqp/lib --libpath=. /home/dan/Source/perl6/rakudo/perl6.moarvm --nqp-lib=blib -e my\ $c\ =\ Channel.new;
==13643== \ \ \ \ my\ @proms\ =\ (1..100).map:\ -\>\ $i\ {
==13643== \ \ \ \ \ \ \ \ start\ {
==13643== \ \ \ \ \ \ \ \ \ \ \ \ await($c)\ +\ await($c)
==13643== \ \ \ \ \ \ \ \ }
==13643== \ \ \ \ };
==13643== \ \ \ \ for\ 1..100\ {
==13643== \ \ \ \ \ \ \ \ $c.send($_);
==13643== \ \ \ \ }
==13643== \ \ \ \ $c.close;
==13643== \ \ \ \ #?rakudo.jvm\ skip\ hangs on JVM
==13643== \ \ \ \ throws-like\ {\ await\ @proms\ },\ X::Channel::ReceiveOnClosed
==13643== 
==13643== Thread 5:
==13643== Invalid read of size 8
==13643==    at 0x5016878: shift (ConcBlockingQueue.c:205)
==13643==    by 0x4FBF2DE: MVM_interp_run (interp.c:2278)
==13643==    by 0x4FCF5EE: start_thread (threads.c:78)
==13643==    by 0x509EF86: uv__thread_start (thread.c:49)
==13643==    by 0x5CDB048: start_thread (in /usr/lib/libpthread-2.25.so)
==13643==  Address 0x8 is not stack'd, malloc'd or (recently) free'd
==13643== 
==13643== 
==13643== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==13643==  Access not within mapped region at address 0x8
==13643==    at 0x5016878: shift (ConcBlockingQueue.c:205)
==13643==    by 0x4FBF2DE: MVM_interp_run (interp.c:2278)
==13643==    by 0x4FCF5EE: start_thread (threads.c:78)
==13643==    by 0x509EF86: uv__thread_start (thread.c:49)
==13643==    by 0x5CDB048: start_thread (in /usr/lib/libpthread-2.25.so)
==13643==  If you believe this happened as a result of a stack
==13643==  overflow in your program's main thread (unlikely but
==13643==  possible), you can try to increase the size of the
==13643==  main thread stack using the --main-stacksize= flag.
==13643==  The main thread stack size used in this run was 8388608.
==13643== 
==13643== HEAP SUMMARY:
==13643==     in use at exit: 113,137,326 bytes in 173,029 blocks
==13643==   total heap usage: 241,839 allocs, 68,810 frees, 131,073,503 bytes allocated
==13643== 
==13643== LEAK SUMMARY:
==13643==    definitely lost: 0 bytes in 0 blocks
==13643==    indirectly lost: 0 bytes in 0 blocks
==13643==      possibly lost: 409,400 bytes in 7,252 blocks
==13643==    still reachable: 112,727,926 bytes in 165,777 blocks
==13643==         suppressed: 0 bytes in 0 blocks
==13643== Rerun with --leak-check=full to see details of leaked memory
==13643== 
==13643== For counts of detected and suppressed errors, rerun with: -v
==13643== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
./perl6-valgrind-m: line 11: 13643 Segmentation fault      (core dumped) valgrind /home/dan/Source/perl6/install/bin/moar --full-cleanup --execname="$0" --libpath="/home/dan/Source/perl6/install/share/nqp/lib" --libpath="/home/dan/Source/perl6/install/share/nqp/lib" --libpath="." /home/dan/Source/perl6/rakudo/perl6.moarvm --nqp-lib=blib "$@"
```

**Comment by dogbert17** [comment]
Almost certainly fixed by 5d346b8dfba0758.

**Comment by dogbert17** [comment]
Unfortunately the problem still persists as of Aug 17, 2017

    This Rakudo version is 2017.07.191.ga.45.ede.9.ca built on MoarVM version 2017.07.444.g.88.c.6851.f,
running on ubuntu (14.04.3.LTS.Trusty.Tahr) / linux (3.19.0.32.generic)

(gdb) r
    Starting program: /home/dogbert/repos/rakudo/install/bin/moar --execname=./perl6-gdb-m --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=. /home/dogbert/repos/rakudo/perl6.moarvm --nqp-lib=blib t/spec/S17-promise/nonblocking-await.t
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
    [New Thread 0xb784db40 (LWP 25521)]
    1..19
    [New Thread 0xb4cffb40 (LWP 25522)]
    [New Thread 0xb42ffb40 (LWP 25523)]
    [New Thread 0xb38ffb40 (LWP 25524)]
    [New Thread 0xb2effb40 (LWP 25525)]
    ok 1 - Recursion creating a deep await-tree completes correctly
        1..3
        ok 1 - code dies
        ok 2 - right exception type (Exception)
        ok 3 - .message matches oopsy
    ok 2 - Deep Promise tree conveys exception up to the top
    [New Thread 0xb1effb40 (LWP 25526)]
    [Switching to Thread 0xb4cffb40 (LWP 25522)]
    
    Breakpoint 1, MVM_panic (exitCode=1, messageFormat=0xb7d11680 "Collectable %p in fromspace accessed") at src/core/exceptions.c:688
    688	    fprintf(stderr, "MoarVM panic: ");
    (gdb) bt
    #0  MVM_panic (exitCode=1, messageFormat=0xb7d11680 "Collectable %p in fromspace accessed") at src/core/exceptions.c:688
    #1  0xb7bc1db3 in check_reg (tc=0xaa508b8, reg_base=0xb3927258, idx=7) at src/core/interp.c:15
    #2  0xb7bdcb69 in MVM_interp_run (tc=0xaa508b8, initial_invoke=0xb7c070b7 <thread_initial_invoke>, invoke_data=0xaa50280) at src/core/interp.c:2985
    #3  0xb7c071cf in start_thread (data=0xaa50280) at src/core/threads.c:83
    #4  0xb7d0c317 in uv.thread_start () from //home/dogbert/repos/rakudo/install/lib/libmoar.so
    #5  0xb7907f72 in start_thread (arg=0xb4cffb40) at pthread_create.c:312
    #6  0xb7a523ee in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129
    (gdb) info threads
      Id   Target Id         Frame 
      7    Thread 0xb1effb40 (LWP 25526) "moar" 0xb7fdccb0 in ?? ()
      6    Thread 0xb2effb40 (LWP 25525) "moar" 0xb7fdccb0 in ?? ()
      5    Thread 0xb38ffb40 (LWP 25524) "moar" _int_free (av=0xb2f00010, p=0xb2fbcc70, have_lock=0) at malloc.c:3899
      4    Thread 0xb42ffb40 (LWP 25523) "moar" 0xb7fdccb0 in ?? ()
    * 3    Thread 0xb4cffb40 (LWP 25522) "moar" MVM_panic (exitCode=1, messageFormat=0xb7d11680 "Collectable %p in fromspace accessed") at src/core/exceptions.c:688
      2    Thread 0xb784db40 (LWP 25521) "moar" 0xb7fdccb0 in ?? ()
      1    Thread 0xb78f1700 (LWP 25520) "moar" 0xb7fdccb0 in ?? ()
    (gdb) t 5
    [Switching to thread 5 (Thread 0xb38ffb40 (LWP 25524))]
    #0  _int_free (av=0xb2f00010, p=0xb2fbcc70, have_lock=0) at malloc.c:3899
    3899	malloc.c: No such file or directory.
    (gdb) bt
    #0  _int_free (av=0xb2f00010, p=0xb2fbcc70, have_lock=0) at malloc.c:3899
    #1  0xb7c60391 in MVM_free (p=0xb2fbcc78) at src/core/alloc.h:40
    #2  0xb7c609b7 in gc_free (tc=0xb3951618, obj=0xb240f798) at src/6model/reprs/MVMCallCapture.c:67
    #3  0xb7c2826d in MVM_gc_collect_free_nursery_uncopied (tc=0xb3951618, limit=0xb2440010) at src/gc/collect.c:581
    #4  0xb7c1fb8b in finish_gc (tc=0xb3951618, gen=0 '\000', is_coordinator=1 '\001') at src/gc/orchestrate.c:230
    #5  0xb7c1ff5e in run_gc (tc=0xb3951618, what_to_do=0 '\000') at src/gc/orchestrate.c:358
    #6  0xb7c20318 in MVM_gc_enter_from_allocator (tc=0xb3951618) at src/gc/orchestrate.c:466
    #7  0xb7c206d6 in MVM_gc_allocate_nursery (tc=0xb3951618, size=28) at src/gc/allocation.c:32
    #8  0xb7c205eb in MVM_gc_allocate (tc=0xb3951618, size=28) at src/gc/allocation.h:13
    #9  0xb7c2073e in MVM_gc_allocate_zeroed (tc=0xb3951618, size=28) at src/gc/allocation.c:49
    #10 0xb7c20a0e in MVM_gc_allocate_object (tc=0xb3951618, st=0x8bf9f20) at src/gc/allocation.c:86
    #11 0xb7bd1f0e in MVM_interp_run (tc=0xb3951618, initial_invoke=0xb7c070b7 <thread_initial_invoke>, invoke_data=0xb39508c8) at src/core/interp.c:1842
    #12 0xb7c071cf in start_thread (data=0xb39508c8) at src/core/threads.c:83
    #13 0xb7d0c317 in uv.thread_start () from //home/dogbert/repos/rakudo/install/lib/libmoar.so
    #14 0xb7907f72 in start_thread (arg=0xb38ffb40) at pthread_create.c:312

**Comment by MasterDuke17** [comment]
Here's another newer one:
```
================================================================================================
This is Rakudo Perl 6 running in valgrind, a tool for debugging and profiling programs.
Running a program in valgrind usually takes *a lot* more time than running it directly,
so please be patient.
This Rakudo version is 2017.07.208.gccf.6.da.9.e.4 built on MoarVM version 2017.07.467.gf.22.f.8.d.7.c,
running on ubuntu (17.04.Zesty.Zapus) / linux (4.10.0.28.generic)
------------------------------------------------------------------------------------------------
==19564== Memcheck, a memory error detector
==19564== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==19564== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==19564== Command: /home/dan/Source/perl6/install/bin/moar --full-cleanup --execname=./perl6-valgrind-m --libpath=/home/dan/Source/perl6/install/share/nqp/lib --libpath=/home/dan/Source/perl6/install/share/nqp/lib --libpath=. /home/dan/Source/perl6/rakudo/perl6.moarvm --nqp-lib=blib t/spec/S17-promise/nonblocking-await.t
==19564== 
1..19
ok 1 - Recursion creating a deep await-tree completes correctly
    1..3
    ok 1 - code dies
    ok 2 - right exception type (Exception)
    ok 3 - .message matches oopsy
ok 2 - Deep Promise tree conveys exception up to the top
ok 3 - Hundreds of time-based Promises awaited completes correctly
ok 4 - await of multiple Promises suspends until all ready
ok 5 - Hundred of await on time/manual Promise completes corectly
ok 6 - await of multiple Promises suspends until all ready
    1..3
    ok 1 - code dies
    ok 2 - right exception type (X::AdHoc)
    ok 3 - .message matches bust
ok 7 - Multiple await also conveys errors correctly
ok 8 - Hundred of outstanding awaits on supplies works
    1..3
    ok 1 - code dies
    ok 2 - right exception type (Exception)
    ok 3 - .message matches strewth
ok 9 - Hundred of outstanding awaits on supplies that die works
ok 10 - Hundred of outstanding awaits on channels works
    1..2
    ok 1 - code dies
    ok 2 - right exception type (X::Channel::ReceiveOnClosed)
ok 11 - Hundred of outstanding awaits on channels that gets closed works
ok 12 - Exception from awaiting broken Promise does X::Await::Died
ok 13 - Exception contains original exception message
ok 14 - Exception contains stack location where Promise code died
ok 15 - Exception contains stack location where we awaited
ok 16 - Exception from awaiting many things, where on dies, does X::Await::Died
ok 17 - Exception contains original exception message
ok 18 - Exception contains stack location where Promise code died
ok 19 - Exception contains stack location where we awaited
==19564== Thread 2:
==19564== Invalid read of size 8
==19564==    at 0x5018F8D: shift (ConcBlockingQueue.c:205)
==19564==    by 0x4FFA2F1: MVM_repr_shift_o (reprconv.c:425)
==19564==    by 0x50482CA: worker (worker.c:13)
==19564==    by 0x4FD4AA0: thread_initial_invoke (threads.c:59)
==19564==    by 0x4FB29FE: MVM_interp_run (interp.c:88)
==19564==    by 0x4FD4B07: start_thread (threads.c:83)
==19564==    by 0x50A9326: uv__thread_start (in /home/dan/Source/perl6/install/lib/libmoar.so)
==19564==    by 0x5D026D9: start_thread (pthread_create.c:456)
==19564==  Address 0x8 is not stack'd, malloc'd or (recently) free'd
==19564== 
==19564== 
==19564== Process terminating with default action of signal 11 (SIGSEGV)
==19564==  Access not within mapped region at address 0x8
==19564==    at 0x5018F8D: shift (ConcBlockingQueue.c:205)
==19564==    by 0x4FFA2F1: MVM_repr_shift_o (reprconv.c:425)
==19564==    by 0x50482CA: worker (worker.c:13)
==19564==    by 0x4FD4AA0: thread_initial_invoke (threads.c:59)
==19564==    by 0x4FB29FE: MVM_interp_run (interp.c:88)
==19564==    by 0x4FD4B07: start_thread (threads.c:83)
==19564==    by 0x50A9326: uv__thread_start (in /home/dan/Source/perl6/install/lib/libmoar.so)
==19564==    by 0x5D026D9: start_thread (pthread_create.c:456)
==19564==  If you believe this happened as a result of a stack
==19564==  overflow in your program's main thread (unlikely but
==19564==  possible), you can try to increase the size of the
==19564==  main thread stack using the --main-stacksize= flag.
==19564==  The main thread stack size used in this run was 8388608.
==19564== 
==19564== HEAP SUMMARY:
==19564==     in use at exit: 129,635,775 bytes in 239,963 blocks
==19564==   total heap usage: 943,509 allocs, 703,546 frees, 347,894,115 bytes allocated
==19564== 
==19564== LEAK SUMMARY:
==19564==    definitely lost: 143,496 bytes in 4,596 blocks
==19564==    indirectly lost: 856 bytes in 30 blocks
==19564==      possibly lost: 406,856 bytes in 7,245 blocks
==19564==    still reachable: 129,084,567 bytes in 228,092 blocks
==19564==         suppressed: 0 bytes in 0 blocks
==19564== Rerun with --leak-check=full to see details of leaked memory
==19564== 
==19564== For counts of detected and suppressed errors, rerun with: -v
==19564== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```
