### ISSUE TITLE
SEGV when trying to create a heap profile with HTTP::UserAgent

### ISSUE THREAD

**Issue by MasterDuke17** [MoarVM/MoarVM#571]
First I just ran this, and got a SEGV: `perl6-m --profile=heap -I modules/http-useragent/lib/ -e 'use HTTP::UserAgent; my $ua = HTTP::UserAgent.new; my $response = $ua.get("https://perl6.org"); say $response.content.chars' `

Then I ran the same thing with `perl6-valgrind-m`, here's the output: https://gist.github.com/MasterDuke17/772785122d8f77dfd0c76d4d23341252

Then I ran a `perl6-valgrind-m` without the `--profile=heap` and got a lot of the same output: https://gist.github.com/MasterDuke17/d44110947d926c56182fc99bea2d9bb5

**Comment by matiaslina** [comment]
I just found the the same problem except for running perl6-m with `--profile` instead of `--profile=heap`.

`perl6-m  --profile -e 'use HTTP::UserAgent; my $ua = HTTP::UserAgent.new; (^10).map: { say $_; $ua.get("https://perl6.org"); }'`

After the eighth iteration I get the SIGSEGV.

```
% perl6-m --profile test.p6                                                                                    
0
1
...
7
8
Segmentation fault (core dumped)
```

Is there any info to attach that could be helpful?

**Comment by MasterDuke17** [comment]
@matiaslina if you use perl6-valgrind-m its output would be good. Or perhaps perl6-gdb-m and then type `bt` after it segfaults.

**Comment by matiaslina** [comment]
[here they are](https://gist.github.com/matiaslina/e9b2a738e46e694dabb7fe46da618360) (valgrind and gdb outputs) :)

**Comment by MasterDuke17** [comment]
Thanks. I just got some more info myself (MoarVM built with `--debug=3 --optimize=0`.

```
================================================================================================
This is Rakudo Perl 6 running in the GNU debugger, which often allows the user to generate useful back-
traces to debug or report issues in Rakudo, the MoarVM backend or the currently running code.

This Rakudo version is 2017.03.106.g.94.cb.73.b.9.b built on MoarVM version 2017.03.87.g.5.d.73.bf.4.b,
running on arch (4.9.3.1.arch) / linux (4.10.6.1.ARCH)

Type `bt full` to generate a backtrace if applicable, type `q` to quit or `help` for help.
------------------------------------------------------------------------------------------------
Reading symbols from /home/dan/Source/perl6/install/bin/moar...done.
MoarVM string pretty printer registered
moar-heap registered
diff-moar-heap registered
Starting program: /home/dan/Source/perl6/install/bin/moar --execname=./install/bin/perl6-gdb-m --libpath=/home/dan/Source/perl6/install/share/nqp/lib --libpath=/home/dan/Source/perl6/install/share/perl6/lib --libpath=/home/dan/Source/perl6/install/share/perl6/runtime /home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm --profile -e use\ HTTP::UserAgent\;\ my\ \$ua\ =\ HTTP::UserAgent.new\;\ \(\^10\).map:\ \{\ say\ \$_\;\ \$ua.get\(\"https://perl6.org\"\)\;\ \}
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0
1
2
3
4
5
6
7
8

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff317fd99 in ?? ()
(gdb) bt
#0  0x00007ffff317fd99 in ?? ()
#1  0x0000000004843a00 in ?? ()
#2  0x00000000006037e0 in ?? ()
#3  0x00007fffffffcb60 in ?? ()
#4  0x00007ffff77ca164 in add_to_bin_freelist (tc=0x7ffff7fd5010, al=0x7fffffffcc20, bin=32767, to_free=0x78) at src/core/fixedsizealloc.c:209
#5  0x00007ffff78659f3 in MVM_jit_enter_code (tc=0x6037e0, cu=0x77f380, code=0x478b6c0) at src/jit/compile.c:139
#6  0x00007ffff77a8797 in MVM_interp_run (tc=0x6037e0, initial_invoke=0x7ffff78913f5 <toplevel_initial_invoke>, invoke_data=0x668330) at src/core/interp.c:5584
#7  0x00007ffff7891518 in MVM_vm_run_file (instance=0x603010, filename=0x7fffffffe80c "/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm") at src/moar.c:323
#8  0x0000000000400f03 in main (argc=9, argv=0x7fffffffe378) at src/main.c:213
(gdb) info threadas
Undefined info command: "threadas".  Try "help info".
(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 0x7ffff7f9e580 (LWP 17176) "moar" 0x00007ffff317fd99 in ?? ()
(gdb) call MVM_dump_backtrace(tc)
No symbol "tc" in current context.
(gdb) up
#1  0x0000000004843a00 in ?? ()
(gdb) call MVM_dump_backtrace(tc)
No symbol "tc" in current context.
(gdb) up
#2  0x00000000006037e0 in ?? ()
(gdb) call MVM_dump_backtrace(tc)
No symbol "tc" in current context.
(gdb) up
#3  0x00007fffffffcb60 in ?? ()
(gdb) call MVM_dump_backtrace(tc)
No symbol "tc" in current context.
(gdb) up
#4  0x00007ffff77ca164 in add_to_bin_freelist (tc=0x7ffff7fd5010, al=0x7fffffffcc20, bin=32767, to_free=0x78) at src/core/fixedsizealloc.c:209
209         if (MVM_instance_have_user_threads(tc)) {
(gdb) call MVM_dump_backtrace(tc)

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff777b0c1 in MVM_gc_root_temp_push (tc=0x7ffff7fd5010, obj_ref=0x7fffffffca48) at src/gc/roots.h:21
21              tc->temproots[tc->num_temproots] = obj_ref;
The program being debugged was signaled while in a function called from GDB.
GDB remains in the frame where the signal was received.
To change this behavior use "set unwindonsignal on".
Evaluation of the expression containing the function
(MVM_dump_backtrace) will be abandoned.
When the function is done executing, GDB will silently stop.
(gdb) 
```

**Comment by timo** [comment]
Could you re-run with MVM_JIT_DISABLE set? the stack trace is pretty
useless with the no-name frames and all that.

**Comment by MasterDuke17** [comment]
```
[dan@alexandria p6]$ MVM_JIT_DISABLE=1 ./install/bin/perl6-gdb-m --profile -e 'use HTTP::UserAgent; my $ua = HTTP::UserAgent.new; (^10).map: { say $_; $ua.get("https://perl6.org"); }'
================================================================================================
This is Rakudo Perl 6 running in the GNU debugger, which often allows the user to generate useful back-
traces to debug or report issues in Rakudo, the MoarVM backend or the currently running code.

This Rakudo version is 2017.03.106.g.94.cb.73.b.9.b built on MoarVM version 2017.03.87.g.5.d.73.bf.4.b,
running on arch (4.9.3.1.arch) / linux (4.10.6.1.ARCH)

Type `bt full` to generate a backtrace if applicable, type `q` to quit or `help` for help.
------------------------------------------------------------------------------------------------
Reading symbols from /home/dan/Source/perl6/install/bin/moar...done.
MoarVM string pretty printer registered
moar-heap registered
diff-moar-heap registered
Starting program: /home/dan/Source/perl6/install/bin/moar --execname=./install/bin/perl6-gdb-m --libpath=/home/dan/Source/perl6/install/share/nqp/lib --libpath=/home/dan/Source/perl6/install/share/perl6/lib --libpath=/home/dan/Source/perl6/install/share/perl6/runtime /home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm --profile -e use\ HTTP::UserAgent\;\ my\ \$ua\ =\ HTTP::UserAgent.new\;\ \(\^10\).map:\ \{\ say\ \$_\;\ \$ua.get\(\"https://perl6.org\"\)\;\ \}
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0
1
2
3
4
5
6
7
8

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff77a6b88 in MVM_interp_run (tc=0x6037e0, initial_invoke=0x7ffff78913f5 <toplevel_initial_invoke>, invoke_data=0x668330) at src/core/interp.c:5352
5352                    tc->cur_frame->params.named_used[GET_UI16(cur_op, 0)] = 1;
(gdb) bt
#0  0x00007ffff77a6b88 in MVM_interp_run (tc=0x6037e0, initial_invoke=0x7ffff78913f5 <toplevel_initial_invoke>, invoke_data=0x668330) at src/core/interp.c:5352
#1  0x00007ffff7891518 in MVM_vm_run_file (instance=0x603010, filename=0x7fffffffe7fa "/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm") at src/moar.c:323
#2  0x0000000000400f03 in main (argc=9, argv=0x7fffffffe358) at src/main.c:213
(gdb) call MVM_dump_backtrace(tc)
   at <unknown>:1  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:!cursor_init)
 from SETTING::src/core/Grammar.pm:64  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.setting.moarvm:cursor-init)
 from SETTING::src/core/Grammar.pm:7  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.setting.moarvm:parse)
 from home#sources/79F4576C6F752E5C28370FA9256C02F086F840C0 (IETF::RFC_Grammar):21  (/home/dan/.perl6/precomp/DF799F74063839F97083E1109DD06B0000D186C0.1491131878.99493/79/79F4576C6F752E5C28370FA9256C02F086F840C0:parse)
 from home#sources/E6932313C3FA27F20E3F940809AFC1198E0EC2E5 (URI):45  (/home/dan/.perl6/precomp/DF799F74063839F97083E1109DD06B0000D186C0.1491131878.99493/E6/E6932313C3FA27F20E3F940809AFC1198E0EC2E5:parse)
 from home#sources/E6932313C3FA27F20E3F940809AFC1198E0EC2E5 (URI):130  (/home/dan/.perl6/precomp/DF799F74063839F97083E1109DD06B0000D186C0.1491131878.99493/E6/E6932313C3FA27F20E3F940809AFC1198E0EC2E5:new)
 from home#sources/C63266BDA44F111588305BF30F94010E9CFCB8F8 (HTTP::UserAgent):130  (/home/dan/.perl6/precomp/DF799F74063839F97083E1109DD06B0000D186C0.1491131878.99493/C6/C63266BDA44F111588305BF30F94010E9CFCB8F8:get)
 from -e:1  (<ephemeral file>:)
 from SETTING::src/core/Any-iterable-methods.pm:475  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/Any-iterable-methods.pm:463  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.setting.moarvm:sink-all)
 from SETTING::src/core/Seq.pm:184  (/home/dan/Source/perl6/install/share/perl6/runtime/CORE.setting.moarvm:sink)
 from -e:1  (<ephemeral file>:<unit>)
 from -e:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1580  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:64  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:run_profiled)
 from gen/moar/stage2/NQPHLL.nqp:1580  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1677  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:1674  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:42  (/home/dan/Source/perl6/install/share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1658  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:47  (/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:38  (/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/dan/Source/perl6/install/share/perl6/runtime/perl6.moarvm:<entry>)
(gdb) 
```
