### ISSUE TITLE
SEGV when attempting to --profile-stage=optimize the 

### ISSUE THREAD

**Issue by MasterDuke17** [MoarVM/MoarVM#813]

**Comment by MasterDuke17** [comment]
Still happens in
`This is Rakudo version 2018.04.1-93-g8ccda1890 built on MoarVM version 2018.04.1-115-ga607c42f1`

**Comment by MasterDuke17** [comment]
No SEGV now, but now a Rakudo/NQP error:
```
[dan@alexandria rakudo]$ "/home/dan/Source/perl6/install/bin/moar" --libpath="blib" --libpath="/home/dan/Source/perl6/install/share/nqp/lib" perl6.moarvm --nqp-lib=blib --setting=NULL --profile-stage=optimize --ll-exception --optimize=3 --target=mbc --stagestats --output=CORE.setting.moarvm gen/moar/CORE.setting
Stage start      :   0.000
Stage parse      :  73.061
Stage syntaxcheck:   0.000
Stage ast        :   0.000
Stage optimize   :  18.024
Stage start      :   0.000
Stage parse      : cannot stringify this
   at gen/moar/stage2/QRegex.nqp:1424  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:!cursor_init)
 from gen/moar/stage2/QRegex.nqp:2304  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:2078  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:2001  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
 from gen/moar/stage2/NQPHLL.nqp:2031  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:2040  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:2057  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1714  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1936  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:1896  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:38  (blib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1821  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:95  (perl6.moarvm:MAIN)
 from gen/moar/main.nqp:60  (perl6.moarvm:<mainline>)
 from <unknown>:1  (perl6.moarvm:<main>)
 from <unknown>:1  (perl6.moarvm:<entry>)
```

**Comment by MasterDuke17** [comment]
After adding some extra debug info to MoarVM, the error is now `Cannot stringify this type (QAST::CompUnit)`

**Comment by MasterDuke17** [comment]
However, `--profile-stage=parse` does cause an immediate SEGV. But running it in gdb just gives an MVM_panic in stage parse.
```
[dan@alexandria rakudo]$ MVM_JIT_DISABLE=1 gdb --args "/home/dan/Source/perl6/install/bin/moar" --libpath="blib" --libpath="/home/dan/Source/perl6/install/share/nqp/lib" perl6.moarvm --nqp-lib=blib --setting=NULL --profile-stage=parse --ll-exception --optimize=3 --target=mbc --stagestats --output=CORE.setting.moarvm gen/moar/CORE.setting
GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/dan/Source/perl6/install/bin/moar...done.
MoarVM string pretty printer registered
moar-heap registered
diff-moar-heap registered
(gdb) b MVM_panic
Function "MVM_panic" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (MVM_panic) pending.
(gdb) r
Starting program: /home/dan/Source/perl6/install/bin/moar --libpath=blib --libpath=/home/dan/Source/perl6/install/share/nqp/lib perl6.moarvm --nqp-lib=blib --setting=NULL --profile-stage=parse --ll-exception --optimize=3 --target=mbc --stagestats --output=CORE.setting.moarvm gen/moar/CORE.setting
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff6ef4700 (LWP 10471)]
Stage start      :   0.000
Stage parse      : 
Thread 1 "moar" hit Breakpoint 1, MVM_panic (exitCode=17, messageFormat=0x7ffff7a7c0d0 "Internal error: invalid thread ID %d in GC work pass") at src/core/exceptions.c:830
830     MVM_NO_RETURN void MVM_panic(MVMint32 exitCode, const char *messageFormat, ...) {
(gdb) bt
#0  MVM_panic (exitCode=17, messageFormat=0x7ffff7a7c0d0 "Internal error: invalid thread ID %d in GC work pass") at src/core/exceptions.c:830
#1  0x00007ffff79064c8 in push_work_to_thread_in_tray (tc=0x55555555acb0, target=1477607344, work=0x555558270d40) at src/gc/collect.c:462
#2  0x00007ffff790671c in pass_leftover_work (tc=0x55555555acb0, wtp=0x7fffffffcc30) at src/gc/collect.c:524
#3  0x00007ffff7904d96 in MVM_gc_collect (tc=0x55555555acb0, what_to_do=0 '\000', gen=1 '\001') at src/gc/collect.c:177
#4  0x00007ffff78fee0e in run_gc (tc=0x55555555acb0, what_to_do=0 '\000') at src/gc/orchestrate.c:410
#5  0x00007ffff78ff27e in MVM_gc_enter_from_allocator (tc=0x55555555acb0) at src/gc/orchestrate.c:527
#6  0x00007ffff78ffaf4 in MVM_gc_allocate_nursery (tc=0x55555555acb0, size=144) at src/gc/allocation.c:35
#7  0x00007ffff78902f9 in fastcreate (tc=0x55555555acb0, cur_op=0x7ffff00ddd4e "\003") at src/core/interp.c:72
#8  0x00007ffff78bd418 in MVM_interp_run (tc=0x55555555acb0, initial_invoke=0x7ffff7a144ff <toplevel_initial_invoke>, invoke_data=0x5555555f7568) at src/core/interp.c:5912
#9  0x00007ffff7a14664 in MVM_vm_run_file (instance=0x55555555a260, filename=0x7fffffffeadf "perl6.moarvm") at src/moar.c:444
#10 0x0000555555555c48 in main (argc=13, argv=0x7fffffffe768) at src/main.c:302
(gdb) f 1
#1  0x00007ffff79064c8 in push_work_to_thread_in_tray (tc=0x55555555acb0, target=1477607344, work=0x555558270d40) at src/gc/collect.c:462
462                 MVM_panic(MVM_exitcode_gcnursery, "Internal error: invalid thread ID %d in GC work pass", target);
(gdb) call MVM_dump_backtrace(tc)
   at gen/moar/stage2/QRegex.nqp:1524  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:!cursor_start_cur)
 from gen/moar/stage2/QRegex.nqp:2014  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:ident)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:identifier)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:name)
 from gen/moar/Perl6-Grammar.nqp:597  (blib/Perl6/Grammar.moarvm:longname)
 from gen/moar/Perl6-Grammar.nqp:3879  (blib/Perl6/Grammar.moarvm:methodop)
 from gen/moar/Perl6-Grammar.nqp:3868  (blib/Perl6/Grammar.moarvm:dottyop)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:dotty:sym<.>)
 from gen/moar/stage2/QRegex.nqp:1691  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:dotty)
 from gen/moar/Perl6-Grammar.nqp:3746  (blib/Perl6/Grammar.moarvm:postfixish)
 from gen/moar/Perl6-Grammar.nqp:3650  (blib/Perl6/Grammar.moarvm:termish)
 from gen/moar/stage2/NQPHLL.nqp:1041  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from gen/moar/Perl6-Grammar.nqp:3675  (blib/Perl6/Grammar.moarvm:EXPR)
 from gen/moar/stage2/NQPHLL.nqp:1263  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:LANG)
 from gen/moar/Perl6-Grammar.nqp:5253  (blib/Perl6/Grammar.moarvm:escape:sym<$>)
 from gen/moar/stage2/QRegex.nqp:1699  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:escape)
 from gen/moar/Perl6-Grammar.nqp:5355  (blib/Perl6/Grammar.moarvm:do_nibbling)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:nibbler)
 from gen/moar/Perl6-Grammar.nqp:259  (blib/Perl6/Grammar.moarvm:nibble)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:quote:sym<dblq>)
 from gen/moar/stage2/QRegex.nqp:1691  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:quote)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:value:sym<quote>)
 from gen/moar/stage2/QRegex.nqp:1691  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:value)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:term:sym<value>)
 from gen/moar/stage2/QRegex.nqp:1691  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:term)
 from gen/moar/Perl6-Grammar.nqp:3639  (blib/Perl6/Grammar.moarvm:termish)
 from gen/moar/stage2/NQPHLL.nqp:1041  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from gen/moar/Perl6-Grammar.nqp:3675  (blib/Perl6/Grammar.moarvm:EXPR)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:arglist)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:args)
 from gen/moar/Perl6-Grammar.nqp:3130  (blib/Perl6/Grammar.moarvm:term:sym<name>)
 from gen/moar/stage2/QRegex.nqp:1691  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:term)
 from gen/moar/Perl6-Grammar.nqp:3639  (blib/Perl6/Grammar.moarvm:termish)
 from gen/moar/stage2/NQPHLL.nqp:1041  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from gen/moar/Perl6-Grammar.nqp:3675  (blib/Perl6/Grammar.moarvm:EXPR)
 from gen/moar/Perl6-Grammar.nqp:956  (blib/Perl6/Grammar.moarvm:statement)
 from gen/moar/Perl6-Grammar.nqp:884  (blib/Perl6/Grammar.moarvm:statementlist)
 from gen/moar/Perl6-Grammar.nqp:1065  (blib/Perl6/Grammar.moarvm:blockoid)
 from gen/moar/Perl6-Grammar.nqp:2435  (blib/Perl6/Grammar.moarvm:routine_def)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:routine_declarator:sym<sub>)
 from gen/moar/stage2/QRegex.nqp:1699  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:routine_declarator)
 from gen/moar/Perl6-Grammar.nqp:2187  (blib/Perl6/Grammar.moarvm:declarator)
 from gen/moar/Perl6-Grammar.nqp:2201  (blib/Perl6/Grammar.moarvm:multi_declarator:sym<multi>)
 from gen/moar/stage2/QRegex.nqp:1699  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:multi_declarator)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:term:sym<multi_declarator>)
 from gen/moar/stage2/QRegex.nqp:1699  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (blib/Perl6/Grammar.moarvm:term)
 from gen/moar/Perl6-Grammar.nqp:3639  (blib/Perl6/Grammar.moarvm:termish)
 from gen/moar/stage2/NQPHLL.nqp:1041  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from gen/moar/Perl6-Grammar.nqp:3675  (blib/Perl6/Grammar.moarvm:EXPR)
 from gen/moar/Perl6-Grammar.nqp:956  (blib/Perl6/Grammar.moarvm:statement)
 from gen/moar/Perl6-Grammar.nqp:884  (blib/Perl6/Grammar.moarvm:statementlist)
 from gen/moar/stage2/NQPHLL.nqp:1263  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:LANG)
 from gen/moar/Perl6-Grammar.nqp:1323  (blib/Perl6/Grammar.moarvm:FOREIGN_LANG)
 from gen/moar/Perl6-Grammar.nqp:826  (blib/Perl6/Grammar.moarvm:comp_unit)
 from gen/moar/Perl6-Grammar.nqp:555  (blib/Perl6/Grammar.moarvm:TOP)
 from gen/moar/stage2/QRegex.nqp:2304  (/home/dan/Source/perl6/install/share/nqp/lib/QRegex.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:2078  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:2001  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
 from gen/moar/stage2/NQPHLL.nqp:2031  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:79  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:run_profiled)
 from <unknown>:1  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:)
 from <unknown>:1  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1714  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1936  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:1866  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:38  (blib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1821  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:82  (perl6.moarvm:MAIN)
 from gen/moar/main.nqp:47  (perl6.moarvm:<mainline>)
 from <unknown>:1  (perl6.moarvm:<main>)
 from <unknown>:1  (perl6.moarvm:<entry>)
(gdb)
```

**Comment by dogbert17** [comment]
Running with MVM_GC_DEBUG=1 gives slightly different information which might possibly be useful:

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ MVM_SPESH_DISABLE=1 gdb --args "/home/dogbert/repos/rakudo/install/bin/moar" --libpath="blib" --libpath="/home/dogbert/repos/rakudo/install/share/nqp/lib" perl6.moarvm --nqp-lib=blib --setting=NULL --profile-stage=parse --ll-exception --optimize=3 --target=mbc --stagestats --output=CORE.setting.moarvm gen/moar/CORE.setting
    GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
    Copyright (C) 2016 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-linux-gnu".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>.
    Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from /home/dogbert/repos/rakudo/install/bin/moar...done.
    (gdb) b MVM_panic
    Function "MVM_panic" not defined.
    Make breakpoint pending on future shared library load? (y or [n]) y
    Breakpoint 1 (MVM_panic) pending.
    (gdb) r
    Starting program: /home/dogbert/repos/rakudo/install/bin/moar --libpath=blib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib perl6.moarvm --nqp-lib=blib --setting=NULL --profile-stage=parse --ll-exception --optimize=3 --target=mbc --stagestats --output=CORE.setting.moarvm gen/moar/CORE.setting
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    Stage start      :   0.000
    Stage parse      : 
    Breakpoint 1, MVM_panic (exitCode=1, messageFormat=0x7ffff7a02598 "Adding pointer %p to past fromspace to GC worklist") at src/core/exceptions.c:830
    830	MVM_NO_RETURN void MVM_panic(MVMint32 exitCode, const char *messageFormat, ...) {
    (gdb) bt
    #0  MVM_panic (exitCode=1, messageFormat=0x7ffff7a02598 "Adding pointer %p to past fromspace to GC worklist") at src/core/exceptions.c:830
    #1  0x00007ffff76702a6 in mark_gc_entries (tc=0x604a60, ptd=0xec1650, worklist=0x3330a60) at src/profiler/instrument.c:807
    #2  0x00007ffff7670613 in MVM_profile_instrumented_mark_data (tc=0x604a60, worklist=0x3330a60) at src/profiler/instrument.c:830
    #3  0x00007ffff754548b in MVM_gc_root_add_tc_roots_to_worklist (tc=0x604a60, worklist=0x3330a60, snapshot=0x0) at src/gc/roots.c:191
    #4  0x00007ffff7548e10 in MVM_gc_collect (tc=0x604a60, what_to_do=0 '\000', gen=0 '\000') at src/gc/collect.c:121
    #5  0x00007ffff753e264 in run_gc (tc=0x604a60, what_to_do=0 '\000') at src/gc/orchestrate.c:410
    #6  0x00007ffff753e6d3 in MVM_gc_enter_from_allocator (tc=0x604a60) at src/gc/orchestrate.c:527
    #7  0x00007ffff753ef4f in MVM_gc_allocate_nursery (tc=0x604a60, size=32) at src/gc/allocation.c:35
    #8  0x00007ffff753ed4a in MVM_gc_allocate (tc=0x604a60, size=32) at src/gc/allocation.h:18
    #9  0x00007ffff753efd8 in MVM_gc_allocate_zeroed (tc=0x604a60, size=32) at src/gc/allocation.c:52
    #10 0x00007ffff753f37b in MVM_gc_allocate_object (tc=0x604a60, st=0x66e448) at src/gc/allocation.c:89
    #11 0x00007ffff751a29d in MVM_box_str (tc=0x604a60, value=0xabca50, type=0x67a908, dst=0x2099648) at src/core/coerce.c:566
    #12 0x00007ffff74d872d in MVM_interp_run (tc=0x604a60, initial_invoke=0x7ffff767b8dc <toplevel_initial_invoke>, invoke_data=0x6a0308) at src/core/interp.c:2173
    #13 0x00007ffff767ba41 in MVM_vm_run_file (instance=0x604010, filename=0x7fffffffe207 "perl6.moarvm") at src/moar.c:444
    #14 0x00000000004016b7 in main (argc=13, argv=0x7fffffffdde8) at src/main.c:302
    (gdb) f 1
    #1  0x00007ffff76702a6 in mark_gc_entries (tc=0x604a60, ptd=0xec1650, worklist=0x3330a60) at src/profiler/instrument.c:807
    807	            MVM_gc_worklist_add(tc, worklist, &(gc->deallocs[ti].type));
    (gdb) p MVM_dump_backtrace(tc)
       at gen/moar/Perl6-Grammar.nqp:1573  (blib/Perl6/Grammar.moarvm:coloncircumfix)
     from gen/moar/Perl6-Grammar.nqp:1615  (blib/Perl6/Grammar.moarvm:colonpair)
     from <unknown>:1  (blib/Perl6/Grammar.moarvm:deflongname)
     from gen/moar/Perl6-Grammar.nqp:2380  (blib/Perl6/Grammar.moarvm:routine_def)
     from <unknown>:1  (blib/Perl6/Grammar.moarvm:routine_declarator:sym<sub>)
     from gen/moar/stage2/QRegex.nqp:1697  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
     from <unknown>:1  (blib/Perl6/Grammar.moarvm:routine_declarator)
     from gen/moar/Perl6-Grammar.nqp:2187  (blib/Perl6/Grammar.moarvm:declarator)
     from gen/moar/Perl6-Grammar.nqp:2201  (blib/Perl6/Grammar.moarvm:multi_declarator:sym<multi>)
     from gen/moar/stage2/QRegex.nqp:1697  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
     from <unknown>:1  (blib/Perl6/Grammar.moarvm:multi_declarator)
     from <unknown>:1  (blib/Perl6/Grammar.moarvm:term:sym<multi_declarator>)
     from gen/moar/stage2/QRegex.nqp:1697  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
     from <unknown>:1  (blib/Perl6/Grammar.moarvm:term)
     from gen/moar/Perl6-Grammar.nqp:3639  (blib/Perl6/Grammar.moarvm:termish)
     from gen/moar/stage2/NQPHLL.nqp:1052  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
     from gen/moar/Perl6-Grammar.nqp:3675  (blib/Perl6/Grammar.moarvm:EXPR)
     from gen/moar/Perl6-Grammar.nqp:956  (blib/Perl6/Grammar.moarvm:statement)
     from gen/moar/Perl6-Grammar.nqp:884  (blib/Perl6/Grammar.moarvm:statementlist)
     from gen/moar/stage2/NQPHLL.nqp:1274  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:LANG)
     from gen/moar/Perl6-Grammar.nqp:1323  (blib/Perl6/Grammar.moarvm:FOREIGN_LANG)
     from gen/moar/Perl6-Grammar.nqp:826  (blib/Perl6/Grammar.moarvm:comp_unit)
     from gen/moar/Perl6-Grammar.nqp:555  (blib/Perl6/Grammar.moarvm:TOP)
     from gen/moar/stage2/QRegex.nqp:2302  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:parse)
     from gen/moar/stage2/NQPHLL.nqp:2095  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:parse)
     from gen/moar/stage2/NQPHLL.nqp:2018  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
     from gen/moar/stage2/NQPHLL.nqp:2048  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:run)
     from gen/moar/stage2/NQPHLL.nqp:84  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:run_profiled)
     from <unknown>:1  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:)
     from <unknown>:1  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:compile)
     from gen/moar/stage2/NQPHLL.nqp:1725  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:eval)
     from gen/moar/stage2/NQPHLL.nqp:1953  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
     from gen/moar/stage2/NQPHLL.nqp:1883  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
     from src/Perl6/Compiler.nqp:38  (blib/Perl6/Compiler.moarvm:command_eval)
     from gen/moar/stage2/NQPHLL.nqp:1838  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_line)
     from gen/moar/main.nqp:82  (perl6.moarvm:MAIN)
     from gen/moar/main.nqp:47  (perl6.moarvm:<mainline>)
     from <unknown>:1  (perl6.moarvm:<main>)
     from <unknown>:1  (perl6.moarvm:<entry>)
    $1 = void
    (gdb)

**Comment by MasterDuke17** [comment]
There's no SEGV anymore, but it dies with an NQP/Rakudo error:
```
[dan@alexandria rakudo]$ /home/dan/Source/perl6/install/bin/moar --libpath=/home/dan/Source/perl6/rakudo/blib --libpath=/home/dan/Source/perl6/install/share/nqp/lib rakudo.moarvm --profile-stage=optimize --setting=NULL.c --ll-exception --optimize=3 --target=mbc --stagestats --output=blib/CORE.c.setting.moarvm gen/moar/CORE.c.setting
Stage start      :   0.000
Stage parse      :  46.109
Stage syntaxcheck:   0.000
Stage ast        :   0.000
Stage optimize   : Cannot stringify object of type QAST::CompUnit
   at src/vm/moar/ModuleLoader.nqp:97  (/home/dan/Source/perl6/install/share/nqp/lib/ModuleLoader.moarvm:)
 from NQP::src/vm/moar/HLL/Backend.nqp:156  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:run_profiled)
 from NQP::src/HLL/Compiler.nqp:490  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:)
 from <unknown>:1  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:compile)
 from NQP::src/HLL/Compiler.nqp:167  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from NQP::src/HLL/Compiler.nqp:423  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from NQP::src/HLL/Compiler.nqp:346  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:234  (/home/dan/Source/perl6/rakudo/blib/Perl6/Compiler.moarvm:command_eval)
 from NQP::src/HLL/Compiler.nqp:269  (/home/dan/Source/perl6/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from src/main.nqp:81  (rakudo.moarvm:MAIN)
 from src/main.nqp:63  (rakudo.moarvm:<mainline>)
 from <unknown>:1  (rakudo.moarvm:<main>)
 from <unknown>:1  (rakudo.moarvm:<entry>)
```
