### ISSUE TITLE
MoarVM Panic when running  t/spec/MISC/bug-coverage.t

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#890]
It should be noted that MVM_GC_DEBUG was set to 1.

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6 -v
    This is Rakudo version 2018.06-56-g72ccd43 built on MoarVM version 2018.06-95-gf66ebd4
    implementing Perl 6.c.
    
    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6-gdb-m t/spec/MISC/bug-coverage.t
    ... skipped a few working runs ...
    (gdb) r
    Starting program: /home/dogbert/repos/rakudo/install/bin/moar --execname=./perl6-gdb-m --libpath=. --libpath=blib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib /home/dogbert/repos/rakudo/perl6.moarvm --nqp-lib=blib t/spec/MISC/bug-coverage.t
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7ffff6251700 (LWP 15490)]
    
    Thread 1 "moar" hit Breakpoint 1, MVM_panic (exitCode=1, messageFormat=0x7ffff7712da0 "Illegal Gen2 -> Nursery in caller chain (not in inter-gen set)") at src/core/exceptions.c:821
    821	MVM_NO_RETURN void MVM_panic(MVMint32 exitCode, const char *messageFormat, ...) {
    (gdb) bt
    #0  MVM_panic (exitCode=1, messageFormat=0x7ffff7712da0 "Illegal Gen2 -> Nursery in caller chain (not in inter-gen set)") at src/core/exceptions.c:821
    #1  0x00007ffff7559e67 in MVM_frame_move_to_heap (tc=0x604a20, frame=0x7ffff7fb9258) at src/core/frame.c:715
    #2  0x00007ffff751c2d7 in MVM_frame_force_to_heap (tc=0x604a20, frame=0x7ffff7fb9258) at src/core/frame.h:193
    #3  0x00007ffff751f3ca in MVM_exception_throw_adhoc_free_va (tc=0x604a20, waste=0x0, 
        messageFormat=0x7ffff7733888 "At Frame %u, Instruction %u, op '%s', operand %u, MAST::Local of wrong type (%u) specified; expected %u", args=0x7fffffffc090) at src/core/exceptions.c:884
    #4  0x00007ffff751f287 in MVM_exception_throw_adhoc (tc=0x604a20, 
        messageFormat=0x7ffff7733888 "At Frame %u, Instruction %u, op '%s', operand %u, MAST::Local of wrong type (%u) specified; expected %u") at src/core/exceptions.c:858
    #5  0x00007ffff76278e3 in compile_operand (tc=0x604a20, ws=0xd7c1470, op_flags=26 '\032', operand=0x7fffea233140) at src/mast/compiler.c:619
    #6  0x00007ffff7629044 in compile_instruction (tc=0x604a20, ws=0xd7c1470, node=0x7fffea233190) at src/mast/compiler.c:811
    #7  0x00007ffff762b245 in compile_frame (tc=0x604a20, ws=0xd7c1470, node=0x7fffea231550, idx=88) at src/mast/compiler.c:1283
    #8  0x00007ffff762c799 in MVM_mast_compile (tc=0x604a20, node=0xda03da0, types=0xd9f6890, size=0x7fffffffc48c) at src/mast/compiler.c:1647
    #9  0x00007ffff762cf3a in MVM_mast_to_cu (tc=0x604a20, mast=0xda03da0, types=0x7fffea455af0, res=0x39cea18) at src/mast/driver.c:37
    #10 0x00007ffff753933a in MVM_interp_run (tc=0x604a20, initial_invoke=0x7ffff76bc9a5 <toplevel_initial_invoke>, invoke_data=0x674ff0) at src/core/interp.c:3193
    #11 0x00007ffff76bcb0a in MVM_vm_run_file (instance=0x604010, filename=0x7fffffffe2c3 "/home/dogbert/repos/rakudo/perl6.moarvm") at src/moar.c:412
    #12 0x00000000004016e7 in main (argc=10, argv=0x7fffffffde28) at src/main.c:299
    (gdb) info threads
      Id   Target Id         Frame 
    * 1    Thread 0x7ffff7fdb700 (LWP 15489) "moar" MVM_panic (exitCode=1, messageFormat=0x7ffff7712da0 "Illegal Gen2 -> Nursery in caller chain (not in inter-gen set)") at src/core/exceptions.c:821
      2    Thread 0x7ffff6251700 (LWP 15490) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
    (gdb) f 1
    #1  0x00007ffff7559e67 in MVM_frame_move_to_heap (tc=0x604a20, frame=0x7ffff7fb9258) at src/core/frame.c:715
    715	    MVM_CHECK_CALLER_CHAIN(tc, new_cur_frame);
    (gdb) p MVM_dump_backtrace(tc)
       at gen/moar/stage2/QAST.nqp:6755  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QAST.moarvm:assemble_and_load)
     from gen/moar/stage2/NQPHLL.nqp:449  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:mbc)
     from gen/moar/stage2/NQPHLL.nqp:1825  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
     from gen/moar/stage2/NQPHLL.nqp:1861  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:run)
     from gen/moar/stage2/NQPHLL.nqp:1864  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:)
     from gen/moar/stage2/NQPHLL.nqp:1850  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:compile)
     from gen/moar/stage2/NQPHLL.nqp:1548  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:eval)
     from gen/moar/stage2/NQPHLL.nqp:1805  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
     from gen/moar/stage2/NQPHLL.nqp:1695  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
     from src/Perl6/Compiler.nqp:42  (blib/Perl6/Compiler.moarvm:command_eval)
     from gen/moar/stage2/NQPHLL.nqp:1654  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_line)
     from gen/moar/main.nqp:47  (/home/dogbert/repos/rakudo/perl6.moarvm:MAIN)
     from gen/moar/main.nqp:38  (/home/dogbert/repos/rakudo/perl6.moarvm:<mainline>)
     from <unknown>:1  (/home/dogbert/repos/rakudo/perl6.moarvm:<main>)
     from <unknown>:1  (/home/dogbert/repos/rakudo/perl6.moarvm:<entry>)
    $1 = void
(gdb)

**Comment by dogbert17** [comment]
Turns out that the problem was caused by a problem in objprimunsigned, where incorrect load sized had been used initially. The problem was reverted in 29cc327f87c9 and properly fixed in 434e4950a77f488e6.
