### ISSUE TITLE
SEGV in t/spec/integration/eval-and-threads.t

### ISSUE THREAD

**Issue by MasterDuke17** [MoarVM/MoarVM#907]
```
dan@alexandria rakudo]$ ./perl6-gdb-m t/spec/integration/eval-and-threads.t
================================================================================================
This is Rakudo Perl 6 running in the GNU debugger, which often allows the user to generate useful back-
traces to debug or report issues in Rakudo, the MoarVM backend or the currently running code.

This Rakudo version is 2018.06.200.g.9.abc.10212 built on MoarVM version 2018.06.228.g.2.f.807.cd.59,
running on arch (4.17.3.1.arch) / linux (4.17.2.1.ARCH)

Type `bt full` to generate a backtrace if applicable, type `q` to quit or `help` for help.
------------------------------------------------------------------------------------------------
Reading symbols from /home/dan/Source/perl6/install/bin/moar...done.
MoarVM string pretty printer registered
moar-heap registered
diff-moar-heap registered
Starting program: /home/dan/Source/perl6/install/bin/moar --execname=./perl6-gdb-m --libpath=. --libpath=blib --libpath=/home/dan/Source/perl6/install/share/nqp/lib --libpath=/home/dan/Source/perl6/install/share/nqp/lib --libpath=/home/dan/Source/perl6/install/share/nqp/lib /home/dan/Source/perl6/rakudo/perl6.moarvm --nqp-lib=blib t/spec/integration/eval-and-threads.t
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff628b700 (LWP 30320)]
1..1
[New Thread 0x7ffff2fec700 (LWP 30321)]
[New Thread 0x7ffff278a700 (LWP 30322)]
[New Thread 0x7ffff3cf1700 (LWP 30323)]
[New Thread 0x7ffff1ade700 (LWP 30324)]

Thread 5 "moar" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3cf1700 (LWP 30323)]
0x00007ffff765f4ca in MVM_sc_create (tc=0x7fffe8066210, handle=<optimized out>) at src/6model/sc.c:11
11          MVMROOT(tc, handle, {
(gdb) bt
#0  0x00007ffff765f4ca in MVM_sc_create (tc=0x7fffe8066210, handle=<optimized out>) at src/6model/sc.c:11
#1  0x00007ffff75db191 in MVM_interp_run (tc=0x7ffff3cf0af0, tc@entry=0x7fffe8066210, initial_invoke=0x55555575d368, invoke_data=0x55555575d368, invoke_data@entry=0x7fffe8065f60) at src/core/interp.c:2988
#2  0x00007ffff75fa536 in start_thread (data=0x7fffe8065f60) at src/core/threads.c:87
#3  0x00007ffff6aa0075 in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007ffff714453f in clone () from /usr/lib/libc.so.6
(gdb)
```
Happens with JIT disabled, spesh disabled, and with both active.

**Comment by MasterDuke17** [comment]
Looks like t/spec/S32-num/stress.t has the same SEGV and backtrace.

**Comment by MasterDuke17** [comment]
These seem to be fixed now. jnthn thinks it was a hash-related fix. @samcv or @dogbert17 have any idea which commit?
