### ISSUE TITLE
SEGV when running t/spec/S02-lexical-conventions/unicode-whitespace.t

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#913]
Stumbled upon a SEGV when running the test file with MVM_SPESH_NODELAY=1 MVM_SPESH_BLOCKING=1. Interestingly, it seems as if the problem disappears if MVM_SPESH_INLINE_DISABLE=1

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6 -v
    This is Rakudo version 2018.06-233-gbf514c1 built on MoarVM version 2018.06-306-g403460e
    implementing Perl 6.c.

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ MVM_SPESH_NODELAY=1 MVM_SPESH_BLOCKING=1 ./perl6-gdb-m t/spec/S02-lexical-conventions/unicode-whitespace.t
    ================================================================================================
    This is Rakudo Perl 6 running in the GNU debugger, which often allows the user to generate useful back-
    traces to debug or report issues in Rakudo, the MoarVM backend or the currently running code.
    
    This Rakudo version is 2018.06.233.gbf.514.c.1 built on MoarVM version 2018.06.306.g.403460.e,
    running on linuxmint (18.3.Sylvia) / linux (4.10.0.38.generic)
    
    Type `bt full` to generate a backtrace if applicable, type `q` to quit or `help` for help.
    ------------------------------------------------------------------------------------------------
    Reading symbols from /home/dogbert/repos/rakudo/nqp/MoarVM/../../install/bin/moar...done.
    Starting program: /home/dogbert/repos/rakudo/install/bin/moar --execname=./perl6-gdb-m --libpath=. --libpath=blib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib /home/dogbert/repos/rakudo/perl6.moarvm --nqp-lib=blib t/spec/S02-lexical-conventions/unicode-whitespace.t
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7ffff6242700 (LWP 3008)]
    1..50
    ok 1 - CHARACTER TABULATION
    ok 2 - LINE FEED (LF)
    ok 3 - LINE TABULATION
    ok 4 - FORM FEED (FF)
    ok 5 - CARRIAGE RETURN (CR)
    
    Thread 1 "moar" received signal SIGSEGV, Segmentation fault.
    0x00007ffff75298ce in MVM_interp_run (tc=0x604a30, initial_invoke=0x7ffff76b6be2 <toplevel_initial_invoke>, invoke_data=0x68f9c0) at src/core/interp.c:2814
    2814	                MVM_ASSIGN_REF(tc, &(((MVMObject *)sf)->header), sf->body.outer, context->static_info);
    (gdb) bt
    #0  0x00007ffff75298ce in MVM_interp_run (tc=0x604a30, initial_invoke=0x7ffff76b6be2 <toplevel_initial_invoke>, invoke_data=0x68f9c0) at src/core/interp.c:2814
    #1  0x00007ffff76b6d47 in MVM_vm_run_file (instance=0x604010, filename=0x7fffffffe281 "/home/dogbert/repos/rakudo/perl6.moarvm") at src/moar.c:412
    #2  0x00000000004016e7 in main (argc=10, argv=0x7fffffffddd8) at src/main.c:299
    (gdb) p context
    $1 = (MVMFrame *) 0x0
    (gdb) info threads
      Id   Target Id         Frame 
    * 1    Thread 0x7ffff7fdb700 (LWP 3004) "moar" 0x00007ffff75298ce in MVM_interp_run (tc=0x604a30, initial_invoke=0x7ffff76b6be2 <toplevel_initial_invoke>, invoke_data=0x68f9c0) at src/core/interp.c:2814
      2    Thread 0x7ffff6242700 (LWP 3008) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
    (gdb) p MVM_dump_backtrace(tc)
       at <unknown>:1  (./CORE.setting.moarvm:EVAL)
     from t/spec/S02-lexical-conventions/unicode-whitespace.t:7  (<ephemeral file>:try_eval)
     from t/spec/S02-lexical-conventions/unicode-whitespace.t:79  (<ephemeral file>:<unit>)
     from t/spec/S02-lexical-conventions/unicode-whitespace.t:1  (<ephemeral file>:<unit-outer>)
     from gen/moar/stage2/NQPHLL.nqp:1566  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:eval)
     from gen/moar/stage2/NQPHLL.nqp:1805  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
     from gen/moar/stage2/NQPHLL.nqp:1695  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
     from src/Perl6/Compiler.nqp:42  (blib/Perl6/Compiler.moarvm:command_eval)
     from gen/moar/stage2/NQPHLL.nqp:1654  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_line)
     from gen/moar/main.nqp:47  (/home/dogbert/repos/rakudo/perl6.moarvm:MAIN)
     from gen/moar/main.nqp:38  (/home/dogbert/repos/rakudo/perl6.moarvm:<mainline>)
     from <unknown>:1  (/home/dogbert/repos/rakudo/perl6.moarvm:<main>)
     from <unknown>:1  (/home/dogbert/repos/rakudo/perl6.moarvm:<entry>)
    $2 = void
    (gdb)

**Comment by dogbert17** [comment]
It looks as if this has been fixed although it's not entirely clear when.
