### ISSUE TITLE
SEGV and weirdness with concurrent I/O

### ISSUE THREAD

**Issue by robertlemmen** [MoarVM/MoarVM#962]
This is somewhat intermittent, but I can reproduce relatively well with the attached "tclient", a golfed version of a bigger piece of code from https://github.com/robertlemmen/p6bench. To run you need some webserver, I use "thttpd -p 6061". The problem seems to happen more frequently with the also attached server written in perl6, probably a timing issue. But it does happen with thttpd as well, so it does not appear to be related to the implementation of the server. the tserver program also seems to trigger the same problem, but less often, probably because it has fewer threads. On my other machine it happens less frequently, but it does happen. I guess the difference is the number of cores, 8 on the machine where the problem occurs more frequently and 4 on the other one.

[tclient.txt](https://github.com/MoarVM/MoarVM/files/2380652/tclient.txt)
[tserver.txt](https://github.com/MoarVM/MoarVM/files/2380653/tserver.txt)

my perl is 2018.08-97-g0a416dadb built on MoarVM version 2018.08-63-ga8dfd4793, and to reproduce I run thttpd or tserver and then "perl6-gdb-m --ll-exception ./tclient". it runs for a while, and then:
```
Thread 159 "moar" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffea4fa9700 (LWP 3335)]
0x00007ffff761d50b in MVM_interp_run (tc=tc@entry=0x7fffd81497f0, initial_invoke=0x7fff5870dd38, 
    invoke_data=0x0, invoke_data@entry=0x7fffd8130360) at src/core/interp.c:3913
warning: Source file is more recent than executable.
3913                    if (ctx->callsite->num_pos != ctx->callsite->arg_count)
(gdb) bt
#0  0x00007ffff761d50b in MVM_interp_run (tc=tc@entry=0x7fffd81497f0, initial_invoke=0x7fff5870dd38, 
    invoke_data=0x0, invoke_data@entry=0x7fffd8130360) at src/core/interp.c:3913
#1  0x00007ffff763ad46 in start_thread (data=0x7fffd8130360) at src/core/threads.c:87
#2  0x00007ffff6b8b494 in start_thread (arg=0x7ffea4fa9700) at pthread_create.c:333
#3  0x00007ffff718dacf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```
At least once I had a case where the stack addresses themselves were broken, but I did not have that recently and failed to record it. 

Sometimes I do not get a segfault but an  exception:
```
Unhandled exception in code scheduled on thread 158
Not enough positional arguments; needed at least 2
  in sub cas at SETTING::src/core/atomicops.pm6 line 22
  in block  at SETTING::src/core/Lock/Async.pm6 line 76
  in method lock at SETTING::src/core/Lock/Async.pm6 line 64
  in method protect at SETTING::src/core/Lock/Async.pm6 line 123
  in block  at SETTING::src/core/IO/Socket/Async.pm6 line 96
  in block  at SETTING::src/core/ThreadPoolScheduler.pm6 line 243
  in block  at SETTING::src/core/ThreadPoolScheduler.pm6 line 242
  in block  at SETTING::src/core/ThreadPoolScheduler.pm6 line 241
  in method run-one at SETTING::src/core/ThreadPoolScheduler.pm6 line 236
  in block  at SETTING::src/core/ThreadPoolScheduler.pm6 line 307
```
looking at the stacktrace of the segfault and the error message here I guess these two are symptoms of the same problem, perhaps some memory corruption. I have played with similar high-concurrency loads, but have been unable to trigger this without async I/O in the mix. Doesn't say much of course...

Please let me know how to debug this further, I am a bit lost at this point.

**Comment by robertlemmen** [comment]
ah darn. fwiw, running under valgrind throuigh the night only made the problem go away...

**Comment by robertlemmen** [comment]
I can reproduce the "not enough positionals", but not the SEGV with this very short version:
```
#!/usr/bin/env perl6

# perhaps playing with these numbers yields something? perhaps interestingly
# I get problems even if threads == 1, so it does not appear to be a problem
# with concurrent access to the same memory. also increasing the nu,ber of 
# locks to an insane number does not make the problem go away.
constant NUM-THREADS = 25;
constant NUM-LOCKS = 25;

my @locks[NUM-LOCKS];
for ^NUM-LOCKS -> $i {
    @locks[$i] = Lock::Async.new;
}

my @threads = (^NUM-THREADS).map: {
    Thread.start(
        sub {
            my $i = NUM-LOCKS.rand.floor;
            @locks[$i].protect({
            });
        }
    )
}
```

**Comment by robertlemmen** [comment]
actually not sure about the above anymore, ignore that

**Comment by dogbert17** [comment]
FWIW, I'm unable to get the example script above to fail on HEAD.

**Comment by robertlemmen** [comment]
same here, and even better my original code that had this problem seems working as well. for the record, I still had the problem on rakudo/moar 2018.08-97-g0a416dadb/2018.08-63-ga8dfd4793, and do not have it anymore on 2018.09-438-g9b23f613c/2018.09-125-g8c2dd3ad2.

Do we know whether this was an intentional fix? If we do not know exactly then I could try to bisect that a bit to find out what was going on...

**Comment by dogbert17** [comment]
I don't think it was an intentional fix, more likely it was a side effect of fixing something else. If it's possible for you to bisect it then that would be great.

I wonder if Rakudo issue 2355 also works. I tried to break it but I didn't have much success there either :)

**Comment by zoffixznet** [comment]
> I can reproduce the "not enough positionals", but not the SEGV with this very short version:

I ran it for a bit and it didn't crash (doesn't exit either, but I'm assuming that's fine).
